/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const GetHealthResponse = zod.strictObject({
  "status": zod.string(),
  "storage": zod.strictObject({
  "bucket": zod.string()
})
})

export const GetByOrgIdProjectsParams = zod.strictObject({
  "orgId": zod.string()
})

export const GetByOrgIdProjectsQueryParams = zod.strictObject({
  "page": zod.string().optional(),
  "pageSize": zod.string().optional(),
  "sort": zod.string().optional()
})

export const GetByOrgIdProjectsResponse = zod.strictObject({
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "orgId": zod.string(),
  "name": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "meta": zod.strictObject({
  "pagination": zod.strictObject({
  "page": zod.number(),
  "pageSize": zod.number(),
  "pageCount": zod.number(),
  "total": zod.number()
})
})
})

export const PostByOrgIdProjectsParams = zod.strictObject({
  "orgId": zod.string()
})

export const PostByOrgIdProjectsBody = zod.strictObject({
  "id": zod.string().optional(),
  "name": zod.string()
})

export const PostByOrgIdProjectsResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "orgId": zod.string(),
  "name": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const GetByOrgIdProjectsByProjectIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const GetByOrgIdProjectsByProjectIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "orgId": zod.string(),
  "name": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const DeleteByOrgIdProjectsByProjectIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const DeleteByOrgIdProjectsByProjectIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const GetByOrgIdProjectsByProjectIdTagsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const GetByOrgIdProjectsByProjectIdTagsQueryParams = zod.strictObject({
  "page": zod.string().optional(),
  "pageSize": zod.string().optional(),
  "sort": zod.string().optional()
})

export const GetByOrgIdProjectsByProjectIdTagsResponse = zod.strictObject({
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "label": zod.string(),
  "normalizedLabel": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "meta": zod.strictObject({
  "pagination": zod.strictObject({
  "page": zod.number(),
  "pageSize": zod.number(),
  "pageCount": zod.number(),
  "total": zod.number()
})
})
})

export const PostByOrgIdProjectsByProjectIdTagsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const PostByOrgIdProjectsByProjectIdTagsBody = zod.strictObject({
  "id": zod.string().optional(),
  "label": zod.string()
})

export const PostByOrgIdProjectsByProjectIdTagsResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "label": zod.string(),
  "normalizedLabel": zod.string(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const GetByOrgIdProjectsByProjectIdChecklistsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const GetByOrgIdProjectsByProjectIdChecklistsQueryParams = zod.strictObject({
  "page": zod.string().optional(),
  "pageSize": zod.string().optional(),
  "sort": zod.string().optional()
})

export const GetByOrgIdProjectsByProjectIdChecklistsResponse = zod.strictObject({
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "title": zod.string(),
  "source": zod.union([zod.string(),zod.null()]),
  "tagsIds": zod.array(zod.string()),
  "options": zod.array(zod.strictObject({
  "label": zod.string(),
  "semantic": zod.string()
})),
  "items": zod.array(zod.looseObject({

})),
  "metadata": zod.looseObject({

}),
  "applicationsCount": zod.number(),
  "completedCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "meta": zod.strictObject({
  "pagination": zod.strictObject({
  "page": zod.number(),
  "pageSize": zod.number(),
  "pageCount": zod.number(),
  "total": zod.number()
})
})
})

export const PostByOrgIdProjectsByProjectIdChecklistsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const PostByOrgIdProjectsByProjectIdChecklistsBody = zod.strictObject({
  "id": zod.string().optional(),
  "title": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "tagsIds": zod.array(zod.string()).optional(),
  "options": zod.array(zod.strictObject({
  "label": zod.string(),
  "semantic": zod.string()
})).optional(),
  "items": zod.array(zod.strictObject({
  "id": zod.string().optional(),
  "position": zod.int().optional(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "tagsIds": zod.array(zod.string()).optional(),
  "parentId": zod.union([zod.string(),zod.null()]).optional(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional(),
  "deletedAt": zod.union([zod.string(),zod.null()]).optional()
})).optional(),
  "metadata": zod.looseObject({

}).optional()
})

export const PostByOrgIdProjectsByProjectIdChecklistsResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "title": zod.string(),
  "source": zod.union([zod.string(),zod.null()]),
  "tagsIds": zod.array(zod.string()),
  "options": zod.array(zod.strictObject({
  "label": zod.string(),
  "semantic": zod.string()
})),
  "items": zod.array(zod.looseObject({

})),
  "metadata": zod.looseObject({

}),
  "applicationsCount": zod.number(),
  "completedCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const GetByOrgIdProjectsByProjectIdChecklistsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const GetByOrgIdProjectsByProjectIdChecklistsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "title": zod.string(),
  "source": zod.union([zod.string(),zod.null()]),
  "tagsIds": zod.array(zod.string()),
  "options": zod.array(zod.strictObject({
  "label": zod.string(),
  "semantic": zod.string()
})),
  "items": zod.array(zod.looseObject({

})),
  "metadata": zod.looseObject({

}),
  "applicationsCount": zod.number(),
  "completedCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const PutByOrgIdProjectsByProjectIdChecklistsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const PutByOrgIdProjectsByProjectIdChecklistsByIdBody = zod.strictObject({
  "id": zod.string().optional(),
  "title": zod.string(),
  "source": zod.union([zod.string(),zod.null()]).optional(),
  "tagsIds": zod.array(zod.string()).optional(),
  "options": zod.array(zod.strictObject({
  "label": zod.string(),
  "semantic": zod.string()
})).optional(),
  "items": zod.array(zod.strictObject({
  "id": zod.string().optional(),
  "position": zod.int().optional(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "tagsIds": zod.array(zod.string()).optional(),
  "parentId": zod.union([zod.string(),zod.null()]).optional(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional(),
  "deletedAt": zod.union([zod.string(),zod.null()]).optional()
})).optional(),
  "metadata": zod.looseObject({

}).optional()
})

export const PutByOrgIdProjectsByProjectIdChecklistsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "title": zod.string(),
  "source": zod.union([zod.string(),zod.null()]),
  "tagsIds": zod.array(zod.string()),
  "options": zod.array(zod.strictObject({
  "label": zod.string(),
  "semantic": zod.string()
})),
  "items": zod.array(zod.looseObject({

})),
  "metadata": zod.looseObject({

}),
  "applicationsCount": zod.number(),
  "completedCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const DeleteByOrgIdProjectsByProjectIdChecklistsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const DeleteByOrgIdProjectsByProjectIdChecklistsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const GetByOrgIdProjectsByProjectIdApplicationsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const GetByOrgIdProjectsByProjectIdApplicationsQueryParams = zod.strictObject({
  "page": zod.string().optional(),
  "pageSize": zod.string().optional(),
  "sort": zod.string().optional(),
  "checklistId": zod.string().optional(),
  "status": zod.string().optional(),
  "from": zod.string().optional(),
  "to": zod.string().optional(),
  "updatedSince": zod.string().optional(),
  "include": zod.string().optional()
})

export const GetByOrgIdProjectsByProjectIdApplicationsResponse = zod.strictObject({
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "checklistId": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "date": zod.string(),
  "status": zod.string(),
  "transcript": zod.union([zod.string(),zod.null()]),
  "gallerySourceApplicationId": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "answeredCount": zod.number(),
  "totalCount": zod.number(),
  "negativeCount": zod.number(),
  "attachmentsCount": zod.number(),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "items": zod.array(zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "completedAt": zod.union([zod.string(),zod.null()])
})),
  "meta": zod.strictObject({
  "pagination": zod.strictObject({
  "page": zod.number(),
  "pageSize": zod.number(),
  "pageCount": zod.number(),
  "total": zod.number()
})
})
})

export const PostByOrgIdProjectsByProjectIdApplicationsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const PostByOrgIdProjectsByProjectIdApplicationsBody = zod.strictObject({
  "id": zod.string().optional(),
  "checklistId": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "date": zod.string(),
  "status": zod.union([zod.literal("draft"),zod.literal("completed")]).optional(),
  "transcript": zod.union([zod.string(),zod.null()]).optional(),
  "gallerySourceApplicationId": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.looseObject({

}).optional(),
  "items": zod.array(zod.strictObject({
  "id": zod.string().optional(),
  "checklistItemId": zod.union([zod.string(),zod.null()]).optional(),
  "parentId": zod.union([zod.string(),zod.null()]).optional(),
  "position": zod.int().optional(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "tagsIds": zod.array(zod.string()).optional(),
  "answer": zod.string().optional(),
  "answeredAt": zod.union([zod.string(),zod.null()]).optional(),
  "note": zod.string().optional(),
  "quantity": zod.union([zod.int(),zod.null()]).optional(),
  "suggested": zod.boolean().optional(),
  "suggestionSource": zod.union([zod.string(),zod.null()]).optional(),
  "workflowStatus": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.looseObject({

}).optional()
})).optional(),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string().optional(),
  "itemId": zod.union([zod.string(),zod.null()]).optional(),
  "name": zod.string(),
  "mimeType": zod.union([zod.string(),zod.null()]).optional(),
  "position": zod.int().optional(),
  "width": zod.union([zod.int(),zod.null()]).optional(),
  "height": zod.union([zod.int(),zod.null()]).optional(),
  "metadata": zod.looseObject({

}).optional()
})).optional()
})

export const PostByOrgIdProjectsByProjectIdApplicationsResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "checklistId": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "date": zod.string(),
  "status": zod.string(),
  "transcript": zod.union([zod.string(),zod.null()]),
  "gallerySourceApplicationId": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "answeredCount": zod.number(),
  "totalCount": zod.number(),
  "negativeCount": zod.number(),
  "attachmentsCount": zod.number(),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "items": zod.array(zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "completedAt": zod.union([zod.string(),zod.null()])
}),
  "meta": zod.looseObject({

})
})

export const GetByOrgIdProjectsByProjectIdApplicationGroupsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const GetByOrgIdProjectsByProjectIdApplicationGroupsQueryParams = zod.strictObject({
  "page": zod.string().optional(),
  "pageSize": zod.string().optional(),
  "checklistId": zod.string(),
  "groupBy": zod.literal("tagSet").optional(),
  "sort": zod.union([zod.literal("recent"),zod.literal("alpha"),zod.literal("numeric")]).optional(),
  "q": zod.string().optional(),
  "applicationsPerGroup": zod.string().optional()
})

export const GetByOrgIdProjectsByProjectIdApplicationGroupsResponse = zod.strictObject({
  "data": zod.array(zod.strictObject({
  "tagsIds": zod.array(zod.string()),
  "applicationsCount": zod.number(),
  "applications": zod.array(zod.strictObject({
  "id": zod.string(),
  "checklistId": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "date": zod.string(),
  "status": zod.string(),
  "transcript": zod.union([zod.string(),zod.null()]),
  "gallerySourceApplicationId": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "answeredCount": zod.number(),
  "totalCount": zod.number(),
  "negativeCount": zod.number(),
  "attachmentsCount": zod.number(),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "items": zod.array(zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "completedAt": zod.union([zod.string(),zod.null()])
}))
})),
  "meta": zod.strictObject({
  "pagination": zod.strictObject({
  "page": zod.number(),
  "pageSize": zod.number(),
  "pageCount": zod.number(),
  "total": zod.number()
})
})
})

export const GetByOrgIdProjectsByProjectIdApplicationsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const GetByOrgIdProjectsByProjectIdApplicationsByIdQueryParams = zod.strictObject({
  "include": zod.string().optional()
})

export const GetByOrgIdProjectsByProjectIdApplicationsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "checklistId": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "date": zod.string(),
  "status": zod.string(),
  "transcript": zod.union([zod.string(),zod.null()]),
  "gallerySourceApplicationId": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "answeredCount": zod.number(),
  "totalCount": zod.number(),
  "negativeCount": zod.number(),
  "attachmentsCount": zod.number(),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "items": zod.array(zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "completedAt": zod.union([zod.string(),zod.null()])
}),
  "meta": zod.looseObject({

})
})

export const PatchByOrgIdProjectsByProjectIdApplicationsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const PatchByOrgIdProjectsByProjectIdApplicationsByIdBody = zod.strictObject({
  "tagsIds": zod.array(zod.string()).optional(),
  "date": zod.string().optional(),
  "transcript": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.union([zod.literal("draft"),zod.literal("completed")]).optional(),
  "gallerySourceApplicationId": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.looseObject({

}).optional(),
  "updatedAt": zod.string().optional()
})

export const PatchByOrgIdProjectsByProjectIdApplicationsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "checklistId": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "date": zod.string(),
  "status": zod.string(),
  "transcript": zod.union([zod.string(),zod.null()]),
  "gallerySourceApplicationId": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "answeredCount": zod.number(),
  "totalCount": zod.number(),
  "negativeCount": zod.number(),
  "attachmentsCount": zod.number(),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "items": zod.array(zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "completedAt": zod.union([zod.string(),zod.null()])
}),
  "meta": zod.looseObject({

})
})

export const DeleteByOrgIdProjectsByProjectIdApplicationsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const DeleteByOrgIdProjectsByProjectIdApplicationsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const PostByOrgIdProjectsByProjectIdApplicationsByIdItemsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const PostByOrgIdProjectsByProjectIdApplicationsByIdItemsBody = zod.strictObject({
  "id": zod.string().optional(),
  "checklistItemId": zod.union([zod.string(),zod.null()]).optional(),
  "parentId": zod.union([zod.string(),zod.null()]).optional(),
  "position": zod.int().optional(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "tagsIds": zod.array(zod.string()).optional(),
  "answer": zod.string().optional(),
  "answeredAt": zod.union([zod.string(),zod.null()]).optional(),
  "note": zod.string().optional(),
  "quantity": zod.union([zod.int(),zod.null()]).optional(),
  "suggested": zod.boolean().optional(),
  "suggestionSource": zod.union([zod.string(),zod.null()]).optional(),
  "workflowStatus": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.looseObject({

}).optional()
})

export const PostByOrgIdProjectsByProjectIdApplicationsByIdItemsResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const PatchByOrgIdProjectsByProjectIdApplicationItemsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const PatchByOrgIdProjectsByProjectIdApplicationItemsByIdBody = zod.strictObject({
  "ids": zod.array(zod.string()).optional(),
  "answer": zod.string().optional(),
  "note": zod.string().optional(),
  "quantity": zod.union([zod.int(),zod.null()]).optional(),
  "tagsIds": zod.array(zod.string()).optional(),
  "suggested": zod.boolean().optional(),
  "suggestionSource": zod.union([zod.string(),zod.null()]).optional(),
  "workflowStatus": zod.union([zod.string(),zod.null()]).optional(),
  "metadata": zod.looseObject({

}).optional(),
  "updatedAt": zod.string().optional()
})

export const PatchByOrgIdProjectsByProjectIdApplicationItemsByIdResponse = zod.strictObject({
  "data": zod.union([zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),zod.array(zod.strictObject({
  "id": zod.string(),
  "position": zod.number(),
  "checklistItemId": zod.union([zod.string(),zod.null()]),
  "parentId": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "description": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "answer": zod.string(),
  "answeredAt": zod.union([zod.string(),zod.null()]),
  "note": zod.string(),
  "quantity": zod.union([zod.number(),zod.null()]),
  "suggested": zod.boolean(),
  "suggestionSource": zod.union([zod.string(),zod.null()]),
  "workflowStatus": zod.union([zod.string(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "attachments": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}))]),
  "meta": zod.looseObject({

})
})

export const PostByOrgIdProjectsByProjectIdApplicationsByIdAttachmentsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const postByOrgIdProjectsByProjectIdApplicationsByIdAttachmentsBodyAttachmentsMax = 100;



export const PostByOrgIdProjectsByProjectIdApplicationsByIdAttachmentsBody = zod.strictObject({
  "attachments": zod.array(zod.strictObject({
  "id": zod.string().optional(),
  "itemId": zod.union([zod.string(),zod.null()]).optional(),
  "name": zod.string(),
  "mimeType": zod.union([zod.string(),zod.null()]).optional(),
  "position": zod.int().optional(),
  "width": zod.union([zod.int(),zod.null()]).optional(),
  "height": zod.union([zod.int(),zod.null()]).optional(),
  "metadata": zod.looseObject({

}).optional()
})).min(1).max(postByOrgIdProjectsByProjectIdApplicationsByIdAttachmentsBodyAttachmentsMax)
})

export const PostByOrgIdProjectsByProjectIdApplicationsByIdAttachmentsResponse = zod.strictObject({
  "data": zod.array(zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "meta": zod.looseObject({

})
})

export const PostByOrgIdProjectsByProjectIdUploadsPresignParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const postByOrgIdProjectsByProjectIdUploadsPresignBodyKeysMax = 100;



export const PostByOrgIdProjectsByProjectIdUploadsPresignBody = zod.strictObject({
  "keys": zod.array(zod.strictObject({
  "attachmentId": zod.string(),
  "contentType": zod.string().optional()
})).min(1).max(postByOrgIdProjectsByProjectIdUploadsPresignBodyKeysMax)
})

export const PostByOrgIdProjectsByProjectIdUploadsPresignResponse = zod.strictObject({
  "data": zod.array(zod.strictObject({
  "key": zod.string(),
  "uploadUrl": zod.string(),
  "method": zod.string(),
  "headers": zod.looseObject({

}),
  "expiresAt": zod.string()
})),
  "meta": zod.looseObject({

})
})

export const PatchByOrgIdProjectsByProjectIdAttachmentsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const PatchByOrgIdProjectsByProjectIdAttachmentsByIdBody = zod.strictObject({
  "uploadStatus": zod.union([zod.literal("pending"),zod.literal("uploaded"),zod.literal("failed")])
})

export const PatchByOrgIdProjectsByProjectIdAttachmentsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string(),
  "applicationId": zod.string(),
  "itemId": zod.union([zod.string(),zod.null()]),
  "position": zod.number(),
  "name": zod.string(),
  "storageKey": zod.union([zod.string(),zod.null()]),
  "uploadStatus": zod.string(),
  "url": zod.union([zod.string(),zod.null()]),
  "sizeBytes": zod.union([zod.number(),zod.null()]),
  "checksum": zod.union([zod.string(),zod.null()]),
  "mimeType": zod.union([zod.string(),zod.null()]),
  "width": zod.union([zod.number(),zod.null()]),
  "height": zod.union([zod.number(),zod.null()]),
  "metadata": zod.looseObject({

}),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const DeleteByOrgIdProjectsByProjectIdAttachmentsByIdParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string(),
  "id": zod.string()
})

export const DeleteByOrgIdProjectsByProjectIdAttachmentsByIdResponse = zod.strictObject({
  "data": zod.strictObject({
  "id": zod.string()
}),
  "meta": zod.looseObject({

})
})

export const GetByOrgIdProjectsByProjectIdReportsTagsParams = zod.strictObject({
  "orgId": zod.string(),
  "projectId": zod.string()
})

export const GetByOrgIdProjectsByProjectIdReportsTagsQueryParams = zod.strictObject({
  "page": zod.string().optional(),
  "pageSize": zod.string().optional(),
  "sort": zod.string().optional(),
  "tagIds": zod.string().optional(),
  "from": zod.string().optional(),
  "to": zod.string().optional()
})

export const GetByOrgIdProjectsByProjectIdReportsTagsResponse = zod.strictObject({
  "data": zod.strictObject({
  "itemProgress": zod.strictObject({
  "answered": zod.number(),
  "total": zod.number()
}),
  "applicationProgress": zod.strictObject({
  "completed": zod.number(),
  "total": zod.number()
}),
  "pendingGroups": zod.array(zod.strictObject({
  "application": zod.strictObject({
  "id": zod.string(),
  "tagsIds": zod.array(zod.string()),
  "date": zod.string(),
  "status": zod.string()
}),
  "items": zod.array(zod.strictObject({
  "itemId": zod.string(),
  "itemTitle": zod.string()
}))
}))
}),
  "meta": zod.strictObject({
  "pagination": zod.strictObject({
  "page": zod.number(),
  "pageSize": zod.number(),
  "pageCount": zod.number(),
  "total": zod.number()
})
})
})

/**
 * Sign in with a social provider
 */
export const SocialSignInBody = zod.strictObject({
  "callbackURL": zod.string().optional().describe('Callback URL to redirect to after the user has signed in'),
  "newUserCallbackURL": zod.string().optional(),
  "errorCallbackURL": zod.string().optional().describe('Callback URL to redirect to if an error happens'),
  "provider": zod.union([zod.enum(['apple', 'atlassian', 'cloudflare', 'cognito', 'discord', 'facebook', 'figma', 'github', 'microsoft', 'google', 'huggingface', 'slack', 'spotify', 'twitch', 'twitter', 'dropbox', 'kick', 'linear', 'linkedin', 'gitlab', 'tiktok', 'reddit', 'roblox', 'salesforce', 'vk', 'zoom', 'notion', 'kakao', 'naver', 'line', 'paybin', 'paypal', 'polar', 'railway', 'vercel', 'wechat']),zod.string()]),
  "disableRedirect": zod.boolean().optional().describe('Disable automatic redirection to the provider. Useful for handling the redirection yourself'),
  "idToken": zod.strictObject({
  "token": zod.string().describe('ID token from the provider'),
  "nonce": zod.string().optional().describe('Nonce used to generate the token'),
  "accessToken": zod.string().optional().describe('Access token from the provider'),
  "refreshToken": zod.string().optional().describe('Refresh token from the provider'),
  "expiresAt": zod.number().optional().describe('Expiry date of the token'),
  "user": zod.strictObject({
  "name": zod.strictObject({
  "firstName": zod.string().optional(),
  "lastName": zod.string().optional()
}).optional(),
  "email": zod.string().optional()
}).optional().describe('The user object from the provider. Only available for some providers like Apple.')
}).optional(),
  "scopes": zod.array(zod.string()).optional().describe('Array of scopes to request from the provider. This will override the default scopes passed.'),
  "requestSignUp": zod.boolean().optional().describe('Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider'),
  "loginHint": zod.string().optional().describe('The login hint to use for the authorization code request'),
  "additionalParams": zod.record(zod.string(), zod.string()).optional().describe('Extra query parameters to append to the provider authorization URL (e.g. Cognito identity_provider, Google hd).'),
  "additionalData": zod.record(zod.string(), zod.unknown()).optional()
})

export const socialSignInResponseUserEmailVerifiedDefault = false;

export const SocialSignInResponse = zod.strictObject({
  "token": zod.string().optional(),
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(socialSignInResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}).optional(),
  "url": zod.string().optional(),
  "redirect": zod.boolean()
}).describe('Returns session details when idToken is provided, or an authorize URL otherwise')

export const GetApiAuthCallbackIdParams = zod.strictObject({
  "id": zod.string()
})

export const GetApiAuthCallbackIdResponse = zod.void()

export const PostApiAuthCallbackIdParams = zod.strictObject({
  "id": zod.string()
})

export const PostApiAuthCallbackIdBody = zod.strictObject({
  "code": zod.string().optional(),
  "error": zod.string().optional(),
  "device_id": zod.string().optional(),
  "error_description": zod.string().optional(),
  "state": zod.string().optional(),
  "user": zod.string().optional(),
  "iss": zod.string().optional()
})

export const PostApiAuthCallbackIdResponse = zod.void()

/**
 * Get the current session
 */
export const getSessionResponseUserEmailVerifiedDefault = false;

export const GetSessionResponse = zod.strictObject({
  "session": zod.strictObject({
  "id": zod.string(),
  "expiresAt": zod.iso.datetime({"offset":true}),
  "token": zod.string(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "ipAddress": zod.string().optional(),
  "userAgent": zod.string().optional(),
  "userId": zod.string(),
  "activeOrganizationId": zod.string().optional()
}),
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(getSessionResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
})
}).nullable()

/**
 * Get the current session
 */
export const GetSessionPostBody = zod.looseObject({

})

export const getSessionPostResponseUserEmailVerifiedDefault = false;

export const GetSessionPostResponse = zod.strictObject({
  "session": zod.strictObject({
  "id": zod.string(),
  "expiresAt": zod.iso.datetime({"offset":true}),
  "token": zod.string(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "ipAddress": zod.string().optional(),
  "userAgent": zod.string().optional(),
  "userId": zod.string(),
  "activeOrganizationId": zod.string().optional()
}),
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(getSessionPostResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
})
}).nullable()

/**
 * Sign out the current user
 */
export const SignOutBody = zod.strictObject({
  "callbackURL": zod.string().optional().describe('The URL to redirect to after provider logout'),
  "disableRedirect": zod.boolean().optional().describe('Return the provider logout URL without redirecting'),
  "state": zod.string().optional().describe('State to pass to the provider logout endpoint')
})

export const SignOutResponse = zod.strictObject({
  "success": zod.boolean().optional(),
  "url": zod.string().optional().describe('Provider logout URL when RP-initiated logout is available'),
  "redirect": zod.boolean().optional().describe('Whether the client should redirect to the provider logout URL')
})

/**
 * Sign up a user using email and password
 */
export const SignUpWithEmailAndPasswordBody = zod.strictObject({
  "name": zod.string().describe('The name of the user'),
  "email": zod.string().describe('The email of the user'),
  "password": zod.string().describe('The password of the user'),
  "image": zod.string().optional().describe('The profile image URL of the user'),
  "callbackURL": zod.string().optional().describe('The URL to use for email verification callback'),
  "rememberMe": zod.boolean().optional().describe('If this is false, the session will not be remembered. Default is `true`.')
})

export const SignUpWithEmailAndPasswordResponse = zod.strictObject({
  "token": zod.string().nullish().describe('Authentication token for the session'),
  "user": zod.strictObject({
  "id": zod.string().describe('The unique identifier of the user'),
  "email": zod.email().describe('The email address of the user'),
  "name": zod.string().describe('The name of the user'),
  "image": zod.url().nullish().describe('The profile image URL of the user'),
  "emailVerified": zod.boolean().describe('Whether the email has been verified'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('When the user was created'),
  "updatedAt": zod.iso.datetime({"offset":true}).describe('When the user was last updated')
})
})

/**
 * Sign in with email and password
 */
export const SignInEmailBody = zod.strictObject({
  "email": zod.string().describe('Email of the user'),
  "password": zod.string().describe('Password of the user'),
  "callbackURL": zod.string().optional().describe('Callback URL to use as a redirect for email verification'),
  "rememberMe": zod.boolean().optional().describe('If this is false, the session will not be remembered. Default is `true`.')
})

export const signInEmailResponseUserEmailVerifiedDefault = false;

export const SignInEmailResponse = zod.strictObject({
  "redirect": zod.literal(false),
  "token": zod.string().describe('Session token'),
  "url": zod.string().nullish(),
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(signInEmailResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
})
}).describe('Session response when idToken is provided')

/**
 * Reset the password for a user
 */
export const ResetPasswordBody = zod.strictObject({
  "newPassword": zod.string().describe('The new password to set'),
  "token": zod.string().optional().describe('The token to reset the password')
})

export const ResetPasswordResponse = zod.strictObject({
  "status": zod.boolean().optional()
})

/**
 * Verify the current user's password
 */
export const VerifyPasswordBody = zod.strictObject({
  "password": zod.string().describe('The password to verify')
})

export const VerifyPasswordResponse = zod.strictObject({
  "status": zod.boolean().optional()
})

/**
 * Verify the email of the user
 */
export const GetApiAuthVerifyEmailQueryParams = zod.strictObject({
  "token": zod.string().describe('The token to verify the email'),
  "callbackURL": zod.string().optional().describe('The URL to redirect to after email verification')
})

export const getApiAuthVerifyEmailResponseUserEmailVerifiedDefault = false;

export const GetApiAuthVerifyEmailResponse = zod.strictObject({
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(getApiAuthVerifyEmailResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}),
  "status": zod.boolean().describe('Indicates if the email was verified successfully')
})

/**
 * Send a verification email to the user
 */
export const SendVerificationEmailBody = zod.strictObject({
  "email": zod.string().describe('The email to send the verification email to'),
  "callbackURL": zod.string().nullish().describe('The URL to use for email verification callback')
})

export const SendVerificationEmailResponse = zod.strictObject({
  "status": zod.boolean().optional().describe('Indicates if the email was sent successfully')
})

export const ChangeEmailBody = zod.strictObject({
  "newEmail": zod.string().describe('The new email address to set must be a valid email address'),
  "callbackURL": zod.string().optional().describe('The URL to redirect to after email verification')
})

export const changeEmailResponseUserEmailVerifiedDefault = false;

export const ChangeEmailResponse = zod.strictObject({
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(changeEmailResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}).optional(),
  "status": zod.boolean().describe('Indicates if the request was successful'),
  "message": zod.union([zod.literal('Email updated'),zod.literal('Verification email sent'),zod.literal(null)]).nullish().describe('Status message of the email change process')
})

/**
 * Change the password of the user
 */
export const ChangePasswordBody = zod.strictObject({
  "newPassword": zod.string().describe('The new password to set'),
  "currentPassword": zod.string().describe('The current password is required'),
  "revokeOtherSessions": zod.boolean().optional().describe('Must be a boolean value')
})

export const ChangePasswordResponse = zod.strictObject({
  "token": zod.string().nullish().describe('New session token if other sessions were revoked'),
  "user": zod.strictObject({
  "id": zod.string().describe('The unique identifier of the user'),
  "email": zod.email().describe('The email address of the user'),
  "name": zod.string().describe('The name of the user'),
  "image": zod.url().nullish().describe('The profile image URL of the user'),
  "emailVerified": zod.boolean().describe('Whether the email has been verified'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('When the user was created'),
  "updatedAt": zod.iso.datetime({"offset":true}).describe('When the user was last updated')
})
})

/**
 * Update the current session
 */
export const UpdateSessionBody = zod.record(zod.string(), zod.unknown())

export const UpdateSessionResponse = zod.strictObject({
  "session": zod.strictObject({
  "id": zod.string(),
  "expiresAt": zod.iso.datetime({"offset":true}),
  "token": zod.string(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "ipAddress": zod.string().optional(),
  "userAgent": zod.string().optional(),
  "userId": zod.string(),
  "activeOrganizationId": zod.string().optional()
}).optional()
})

/**
 * Update the current user
 */
export const UpdateUserBody = zod.strictObject({
  "name": zod.string().optional().describe('The name of the user'),
  "image": zod.string().nullish().describe('The image of the user')
})

export const updateUserResponseUserEmailVerifiedDefault = false;

export const UpdateUserResponse = zod.strictObject({
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(updateUserResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
}).optional()
})

/**
 * Delete the user
 */
export const DeleteUserBody = zod.strictObject({
  "callbackURL": zod.string().optional().describe('The callback URL to redirect to after the user is deleted'),
  "password": zod.string().optional().describe('The user\'s password. Required if session is not fresh'),
  "token": zod.string().optional().describe('The deletion verification token')
})

export const DeleteUserResponse = zod.strictObject({
  "success": zod.boolean().describe('Indicates if the operation was successful'),
  "message": zod.enum(['User deleted', 'Verification email sent']).describe('Status message of the deletion process')
})

/**
 * Send a password reset email to the user
 */
export const RequestPasswordResetBody = zod.strictObject({
  "email": zod.string().describe('The email address of the user to send a password reset email to'),
  "redirectTo": zod.string().optional().describe('The URL to redirect the user to reset their password. If the token isn\'t valid or expired, it\'ll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it\'ll be redirected with a query parameter `?token=VALID_TOKEN')
})

export const RequestPasswordResetResponse = zod.strictObject({
  "status": zod.boolean().optional(),
  "message": zod.string().optional()
})

/**
 * Redirects the user to the callback URL with the token
 */
export const ResetPasswordCallbackParams = zod.strictObject({
  "token": zod.string().describe('The token to reset the password')
})

export const ResetPasswordCallbackQueryParams = zod.strictObject({
  "callbackURL": zod.string().describe('The URL to redirect the user to reset their password')
})

export const ResetPasswordCallbackResponse = zod.strictObject({
  "token": zod.string().optional()
})

/**
 * List all active sessions for the user
 */
export const ListUserSessionsResponseItem = zod.strictObject({
  "id": zod.string(),
  "expiresAt": zod.iso.datetime({"offset":true}),
  "token": zod.string(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "ipAddress": zod.string().optional(),
  "userAgent": zod.string().optional(),
  "userId": zod.string(),
  "activeOrganizationId": zod.string().optional()
})
export const ListUserSessionsResponse = zod.array(ListUserSessionsResponseItem)

/**
 * Revoke a single session
 */
export const PostApiAuthRevokeSessionBody = zod.strictObject({
  "token": zod.string().describe('The token to revoke')
})

export const PostApiAuthRevokeSessionResponse = zod.strictObject({
  "status": zod.boolean().describe('Indicates if the session was revoked successfully')
})

/**
 * Revoke all sessions for the user
 */
export const PostApiAuthRevokeSessionsBody = zod.looseObject({

})

export const PostApiAuthRevokeSessionsResponse = zod.strictObject({
  "status": zod.boolean().describe('Indicates if all sessions were revoked successfully')
})

/**
 * Revoke all other sessions for the user except the current one
 */
export const PostApiAuthRevokeOtherSessionsBody = zod.looseObject({

})

export const PostApiAuthRevokeOtherSessionsResponse = zod.strictObject({
  "status": zod.boolean().describe('Indicates if all other sessions were revoked successfully')
})

/**
 * Link a social account to the user
 */
export const LinkSocialAccountBody = zod.strictObject({
  "callbackURL": zod.string().optional().describe('The URL to redirect to after the user has signed in'),
  "provider": zod.union([zod.enum(['apple', 'atlassian', 'cloudflare', 'cognito', 'discord', 'facebook', 'figma', 'github', 'microsoft', 'google', 'huggingface', 'slack', 'spotify', 'twitch', 'twitter', 'dropbox', 'kick', 'linear', 'linkedin', 'gitlab', 'tiktok', 'reddit', 'roblox', 'salesforce', 'vk', 'zoom', 'notion', 'kakao', 'naver', 'line', 'paybin', 'paypal', 'polar', 'railway', 'vercel', 'wechat']),zod.string()]),
  "idToken": zod.strictObject({
  "token": zod.string(),
  "nonce": zod.string().optional(),
  "accessToken": zod.string().optional(),
  "refreshToken": zod.string().optional()
}).optional(),
  "requestSignUp": zod.boolean().optional(),
  "scopes": zod.array(zod.string()).optional().describe('Additional scopes to request from the provider'),
  "errorCallbackURL": zod.string().optional().describe('The URL to redirect to if there is an error during the link process'),
  "disableRedirect": zod.boolean().optional().describe('Disable automatic redirection to the provider. Useful for handling the redirection yourself'),
  "loginHint": zod.string().optional().describe('The login hint to use for the authorization code request'),
  "additionalParams": zod.record(zod.string(), zod.string()).optional().describe('Extra query parameters to append to the provider authorization URL (e.g. Cognito identity_provider, Google hd).'),
  "additionalData": zod.record(zod.string(), zod.unknown()).optional()
})

export const LinkSocialAccountResponse = zod.strictObject({
  "url": zod.string().optional().describe('The authorization URL to redirect the user to'),
  "redirect": zod.boolean().describe('Indicates if the user should be redirected to the authorization URL'),
  "status": zod.boolean().optional()
})

/**
 * List all accounts linked to the user
 */
export const ListUserAccountsResponseItem = zod.strictObject({
  "id": zod.string(),
  "providerId": zod.string(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "accountId": zod.string(),
  "userId": zod.string(),
  "scopes": zod.array(zod.string())
})
export const ListUserAccountsResponse = zod.array(ListUserAccountsResponseItem)

/**
 * Callback to complete user deletion with verification token
 */
export const GetApiAuthDeleteUserCallbackQueryParams = zod.strictObject({
  "token": zod.string().optional(),
  "callbackURL": zod.string().optional()
})

export const GetApiAuthDeleteUserCallbackResponse = zod.strictObject({
  "success": zod.boolean().describe('Indicates if the deletion was successful'),
  "message": zod.enum(['User deleted']).describe('Confirmation message')
})

/**
 * Unlink an account
 */
export const PostApiAuthUnlinkAccountBody = zod.strictObject({
  "accountId": zod.string().describe('The Better Auth account ID to unlink')
})

export const PostApiAuthUnlinkAccountResponse = zod.strictObject({
  "status": zod.boolean().optional()
})

/**
 * Refresh the access token using a refresh token
 */
export const PostApiAuthRefreshTokenBody = zod.union([zod.strictObject({
  "accountId": zod.string().describe('The Better Auth account ID'),
  "userId": zod.string().optional().describe('The user ID associated with the account')
}),zod.strictObject({
  "useAccountCookie": zod.literal(true).describe('Select the current OAuth account from its signed cookie'),
  "userId": zod.string().optional().describe('The user ID associated with the account')
})])

export const PostApiAuthRefreshTokenResponse = zod.strictObject({
  "tokenType": zod.string().optional(),
  "idToken": zod.string().optional(),
  "accessToken": zod.string().optional(),
  "refreshToken": zod.string().optional(),
  "accessTokenExpiresAt": zod.iso.datetime({"offset":true}).optional(),
  "refreshTokenExpiresAt": zod.iso.datetime({"offset":true}).optional()
})

/**
 * Get a valid access token, doing a refresh if needed
 */
export const PostApiAuthGetAccessTokenBody = zod.union([zod.strictObject({
  "accountId": zod.string().describe('The Better Auth account ID'),
  "userId": zod.string().optional().describe('The user ID associated with the account')
}),zod.strictObject({
  "useAccountCookie": zod.literal(true).describe('Select the current OAuth account from its signed cookie'),
  "userId": zod.string().optional().describe('The user ID associated with the account')
})])

export const PostApiAuthGetAccessTokenResponse = zod.strictObject({
  "tokenType": zod.string().optional(),
  "idToken": zod.string().optional(),
  "accessToken": zod.string().optional(),
  "accessTokenExpiresAt": zod.iso.datetime({"offset":true}).optional()
})

/**
 * Get the account info provided by the provider
 */
export const GetApiAuthAccountInfoResponse = zod.strictObject({
  "user": zod.strictObject({
  "name": zod.string().optional(),
  "email": zod.string().nullish(),
  "image": zod.string().optional(),
  "emailVerified": zod.boolean()
}),
  "account": zod.strictObject({
  "id": zod.string(),
  "providerId": zod.string(),
  "accountId": zod.string()
}),
  "data": zod.record(zod.string(), zod.unknown())
})

/**
 * Check if the API is working
 */
export const GetApiAuthOkResponse = zod.strictObject({
  "ok": zod.boolean().describe('Indicates if the API is working')
})

/**
 * Displays an error page
 */
export const GetApiAuthErrorResponse = zod.unknown()

