/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Create an organization
 */




export const PostApiAuthOrganizationCreateBody = zod.strictObject({
  "name": zod.string().min(1).describe('The name of the organization'),
  "slug": zod.string().min(1).describe('The slug of the organization'),
  "userId": zod.string().optional().describe('The user id of the organization creator. If not provided, the current user will be used. Should only be used by admins or when called by the server. server-only. Eg: "user-id"'),
  "logo": zod.string().nullish().describe('The logo of the organization'),
  "metadata": zod.record(zod.string(), zod.unknown()).optional().describe('The metadata of the organization'),
  "keepCurrentActiveOrganization": zod.boolean().optional().describe('Whether to keep the current active organization active after creating a new one. Eg: true')
})

export const PostApiAuthOrganizationCreateResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string(),
  "logo": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "metadata": zod.string().optional()
}).describe('The organization that was created')

/**
 * Update an organization
 */




export const PostApiAuthOrganizationUpdateBody = zod.strictObject({
  "data": zod.strictObject({
  "name": zod.string().min(1).optional().describe('The name of the organization'),
  "slug": zod.string().min(1).optional().describe('The slug of the organization'),
  "logo": zod.string().nullish().describe('The logo of the organization'),
  "metadata": zod.record(zod.string(), zod.unknown()).optional().describe('The metadata of the organization')
}),
  "organizationId": zod.string().optional().describe('The organization ID. Eg: "org-id"')
})

export const PostApiAuthOrganizationUpdateResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string(),
  "logo": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "metadata": zod.string().optional()
}).describe('The updated organization')

/**
 * Delete an organization
 */
export const PostApiAuthOrganizationDeleteBody = zod.strictObject({
  "organizationId": zod.string().describe('The organization id to delete')
})

export const PostApiAuthOrganizationDeleteResponse = zod.string().describe('The organization id that was deleted')

/**
 * Set the active organization
 */
export const SetActiveOrganizationBody = zod.strictObject({
  "organizationId": zod.string().nullish().describe('The organization id to set as active. It can be null to unset the active organization. Eg: "org-id"'),
  "organizationSlug": zod.string().optional().describe('The organization slug to set as active. It can be null to unset the active organization if organizationId is not provided. Eg: "org-slug"')
})

export const SetActiveOrganizationResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string(),
  "logo": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "metadata": zod.string().optional()
}).describe('The organization')

/**
 * Get the organization metadata
 */
export const GetOrganizationResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string(),
  "logo": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "metadata": zod.string().optional()
}).describe('The organization')

/**
 * Get the full organization
 */
export const GetFullOrganizationResponse = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string(),
  "logo": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "metadata": zod.string().optional()
}).describe('The organization')

/**
 * List all organizations
 */
export const GetApiAuthOrganizationListResponseItem = zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "slug": zod.string(),
  "logo": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "metadata": zod.string().optional()
})
export const GetApiAuthOrganizationListResponse = zod.array(GetApiAuthOrganizationListResponseItem)

/**
 * Create an invitation to an organization
 */
export const CreateOrganizationInvitationBody = zod.strictObject({
  "email": zod.string().describe('The email address of the user to invite'),
  "role": zod.union([zod.string().describe('The role to assign to the user'),zod.array(zod.string().describe('The roles to assign to the user'))]).describe('The role(s) to assign to the user. It can be `admin`, `member`, owner. Eg: "member"'),
  "organizationId": zod.string().optional().describe('The organization ID to invite the user to'),
  "resend": zod.boolean().optional().describe('Resend the invitation email, if the user is already invited. Eg: true'),
  "teamId": zod.union([zod.string().describe('The team ID to invite the user to'),zod.array(zod.string()).describe('The team IDs to invite the user to')]).optional()
})

export const CreateOrganizationInvitationResponse = zod.strictObject({
  "id": zod.string(),
  "email": zod.string(),
  "role": zod.string(),
  "organizationId": zod.string(),
  "inviterId": zod.string(),
  "status": zod.string(),
  "expiresAt": zod.string(),
  "createdAt": zod.string()
})

export const PostApiAuthOrganizationCancelInvitationBody = zod.strictObject({
  "invitationId": zod.string().describe('The ID of the invitation to cancel')
})

export const PostApiAuthOrganizationCancelInvitationResponse = zod.void()

/**
 * Accept an invitation to an organization
 */
export const PostApiAuthOrganizationAcceptInvitationBody = zod.strictObject({
  "invitationId": zod.string().describe('The ID of the invitation to accept')
})

export const PostApiAuthOrganizationAcceptInvitationResponse = zod.strictObject({
  "invitation": zod.looseObject({

}).optional(),
  "member": zod.looseObject({

}).optional()
})

/**
 * Get an invitation by ID
 */
export const GetApiAuthOrganizationGetInvitationQueryParams = zod.strictObject({
  "id": zod.string().optional()
})

export const GetApiAuthOrganizationGetInvitationResponse = zod.strictObject({
  "id": zod.string(),
  "email": zod.string(),
  "role": zod.string(),
  "organizationId": zod.string(),
  "inviterId": zod.string(),
  "status": zod.string(),
  "expiresAt": zod.string(),
  "organizationName": zod.string(),
  "organizationSlug": zod.string(),
  "inviterEmail": zod.string()
})

/**
 * Reject an invitation to an organization
 */
export const PostApiAuthOrganizationRejectInvitationBody = zod.strictObject({
  "invitationId": zod.string().describe('The ID of the invitation to reject')
})

export const PostApiAuthOrganizationRejectInvitationResponse = zod.strictObject({
  "invitation": zod.looseObject({

}).optional(),
  "member": zod.looseObject({

}).nullish()
})

export const GetApiAuthOrganizationListInvitationsResponse = zod.void()

/**
 * Get the member details of the active organization
 */
export const GetApiAuthOrganizationGetActiveMemberResponse = zod.strictObject({
  "id": zod.string(),
  "userId": zod.string(),
  "organizationId": zod.string(),
  "role": zod.string()
})

export const PostApiAuthOrganizationCheckSlugBody = zod.strictObject({
  "slug": zod.string().describe('The organization slug to check. Eg: "my-org"')
})

export const PostApiAuthOrganizationCheckSlugResponse = zod.void()

/**
 * Remove a member from an organization
 */
export const PostApiAuthOrganizationRemoveMemberBody = zod.strictObject({
  "memberIdOrEmail": zod.string().describe('The ID or email of the member to remove'),
  "organizationId": zod.string().optional().describe('The ID of the organization to remove the member from. If not provided, the active organization will be used. Eg: "org-id"')
})

export const PostApiAuthOrganizationRemoveMemberResponse = zod.strictObject({
  "member": zod.strictObject({
  "id": zod.string(),
  "userId": zod.string(),
  "organizationId": zod.string(),
  "role": zod.string()
})
})

/**
 * Update the role of a member in an organization
 */
export const UpdateOrganizationMemberRoleBody = zod.strictObject({
  "role": zod.union([zod.string(),zod.array(zod.string())]).describe('The new role to be applied. This can be a string or array of strings representing the roles. Eg: ["admin", "sale"]'),
  "memberId": zod.string().describe('The member id to apply the role update to. Eg: "member-id"'),
  "organizationId": zod.string().optional().describe('An optional organization ID which the member is a part of to apply the role update. If not provided, you must provide session headers to get the active organization. Eg: "organization-id"')
})

export const UpdateOrganizationMemberRoleResponse = zod.strictObject({
  "member": zod.strictObject({
  "id": zod.string(),
  "userId": zod.string(),
  "organizationId": zod.string(),
  "role": zod.string()
})
})

export const PostApiAuthOrganizationLeaveBody = zod.strictObject({
  "organizationId": zod.string().describe('The organization Id for the member to leave. Eg: "organization-id"')
})

export const PostApiAuthOrganizationLeaveResponse = zod.void()

/**
 * List all invitations a user has received
 */
export const GetApiAuthOrganizationListUserInvitationsResponseItem = zod.strictObject({
  "id": zod.string(),
  "email": zod.string(),
  "role": zod.string(),
  "organizationId": zod.string(),
  "organizationName": zod.string(),
  "inviterId": zod.string().describe('The ID of the user who created the invitation'),
  "teamId": zod.string().nullish().describe('The ID of the team associated with the invitation'),
  "status": zod.string(),
  "expiresAt": zod.string(),
  "createdAt": zod.string()
})
export const GetApiAuthOrganizationListUserInvitationsResponse = zod.array(GetApiAuthOrganizationListUserInvitationsResponseItem)

export const GetApiAuthOrganizationListMembersResponse = zod.void()

export const GetApiAuthOrganizationGetActiveMemberRoleResponse = zod.void()

/**
 * Check if the user has permission
 */
export const PostApiAuthOrganizationHasPermissionBody = zod.strictObject({
  "permission": zod.looseObject({

}).optional().describe('The permission to check'),
  "permissions": zod.looseObject({

}).describe('The permission to check')
})

export const PostApiAuthOrganizationHasPermissionResponse = zod.strictObject({
  "error": zod.string().optional(),
  "success": zod.boolean()
})

