/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationAttachment201TwoDataItem } from './addApplicationAttachment201TwoDataItem';
import type { AddApplicationAttachment201TwoMeta } from './addApplicationAttachment201TwoMeta';

export type AddApplicationAttachment201Two = {
  data: AddApplicationAttachment201TwoDataItem[];
  meta: AddApplicationAttachment201TwoMeta;
};
