/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationItem200ThreeData } from './addApplicationItem200ThreeData';
import type { AddApplicationItem200ThreeMeta } from './addApplicationItem200ThreeMeta';

export type AddApplicationItem200Three = {
  data: AddApplicationItem200ThreeData;
  meta: AddApplicationItem200ThreeMeta;
};
