/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationItem200OneData } from './addApplicationItem200OneData';
import type { AddApplicationItem200OneMeta } from './addApplicationItem200OneMeta';

export type AddApplicationItem200One = {
  data: AddApplicationItem200OneData;
  meta: AddApplicationItem200OneMeta;
};
