/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationAttachment201OneDataItem } from './addApplicationAttachment201OneDataItem';
import type { AddApplicationAttachment201OneMeta } from './addApplicationAttachment201OneMeta';

export type AddApplicationAttachment201One = {
  data: AddApplicationAttachment201OneDataItem[];
  meta: AddApplicationAttachment201OneMeta;
};
