/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationAttachment200ThreeDataItem } from './addApplicationAttachment200ThreeDataItem';
import type { AddApplicationAttachment200ThreeMeta } from './addApplicationAttachment200ThreeMeta';

export type AddApplicationAttachment200Three = {
  data: AddApplicationAttachment200ThreeDataItem[];
  meta: AddApplicationAttachment200ThreeMeta;
};
