/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationItem200TwoData } from './addApplicationItem200TwoData';
import type { AddApplicationItem200TwoMeta } from './addApplicationItem200TwoMeta';

export type AddApplicationItem200Two = {
  data: AddApplicationItem200TwoData;
  meta: AddApplicationItem200TwoMeta;
};
