/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationAttachment200OneDataItem } from './addApplicationAttachment200OneDataItem';
import type { AddApplicationAttachment200OneMeta } from './addApplicationAttachment200OneMeta';

export type AddApplicationAttachment200One = {
  data: AddApplicationAttachment200OneDataItem[];
  meta: AddApplicationAttachment200OneMeta;
};
