/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationItem201ThreeData } from './addApplicationItem201ThreeData';
import type { AddApplicationItem201ThreeMeta } from './addApplicationItem201ThreeMeta';

export type AddApplicationItem201Three = {
  data: AddApplicationItem201ThreeData;
  meta: AddApplicationItem201ThreeMeta;
};
