/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationItem201OneData } from './addApplicationItem201OneData';
import type { AddApplicationItem201OneMeta } from './addApplicationItem201OneMeta';

export type AddApplicationItem201One = {
  data: AddApplicationItem201OneData;
  meta: AddApplicationItem201OneMeta;
};
