/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationItem201TwoData } from './addApplicationItem201TwoData';
import type { AddApplicationItem201TwoMeta } from './addApplicationItem201TwoMeta';

export type AddApplicationItem201Two = {
  data: AddApplicationItem201TwoData;
  meta: AddApplicationItem201TwoMeta;
};
