/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationAttachment201ThreeDataItem } from './addApplicationAttachment201ThreeDataItem';
import type { AddApplicationAttachment201ThreeMeta } from './addApplicationAttachment201ThreeMeta';

export type AddApplicationAttachment201Three = {
  data: AddApplicationAttachment201ThreeDataItem[];
  meta: AddApplicationAttachment201ThreeMeta;
};
