/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { AddApplicationAttachmentBodyOneAttachmentsItemMetadata } from './addApplicationAttachmentBodyOneAttachmentsItemMetadata';

export type AddApplicationAttachmentBodyOneAttachmentsItem = {
  id?: string;
  itemId?: string | null;
  name: string;
  mimeType?: string | null;
  position?: number;
  width?: number | null;
  height?: number | null;
  metadata?: AddApplicationAttachmentBodyOneAttachmentsItemMetadata;
};
