/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationItemsItemAttachmentsItem } from './applicationItemsItemAttachmentsItem';
import type { ApplicationItemsItemMetadata } from './applicationItemsItemMetadata';

export type ApplicationItemsItem = {
  id: string;
  position: number;
  checklistItemId: string | null;
  parentId: string | null;
  title: string;
  description: string;
  tagsIds: string[];
  answer: string;
  answeredAt: string | null;
  note: string;
  quantity: number | null;
  suggested: boolean;
  suggestionSource: string | null;
  workflowStatus: string | null;
  metadata: ApplicationItemsItemMetadata;
  attachments: ApplicationItemsItemAttachmentsItem[];
  createdAt: string;
  updatedAt: string;
};
