/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationGroupApplicationsItemAttachmentsItem } from './applicationGroupApplicationsItemAttachmentsItem';
import type { ApplicationGroupApplicationsItemItemsItem } from './applicationGroupApplicationsItemItemsItem';
import type { ApplicationGroupApplicationsItemMetadata } from './applicationGroupApplicationsItemMetadata';

export type ApplicationGroupApplicationsItem = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: ApplicationGroupApplicationsItemMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: ApplicationGroupApplicationsItemAttachmentsItem[];
  items: ApplicationGroupApplicationsItemItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
