/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationAttachmentsItem } from './applicationAttachmentsItem';
import type { ApplicationItemsItem } from './applicationItemsItem';
import type { ApplicationMetadata } from './applicationMetadata';

export interface Application {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: ApplicationMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: ApplicationAttachmentsItem[];
  items: ApplicationItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
}
