/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type ChangeEmailBody = {
  /** The new email address to set must be a valid email address */
  newEmail: string;
  /** The URL to redirect to after email verification */
  callbackURL?: string;
};
