/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type ChangeEmailWithEmailOTPBody = {
  /** New email address to verify and change to */
  newEmail: string;
  /** OTP sent to the new email */
  otp: string;
};
