/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status message of the email change process
 * @nullable
 */
export type ChangeEmail200Message = typeof ChangeEmail200Message[keyof typeof ChangeEmail200Message] | null;


export const ChangeEmail200Message = {
  Email_updated: 'Email updated',
  Verification_email_sent: 'Verification email sent',
} as const;
