/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeEmail200Message } from './changeEmail200Message';
import type { User } from './user';

export type ChangeEmail200 = {
  user?: User;
  /** Indicates if the request was successful */
  status: boolean;
  /**
     * Status message of the email change process
     * @nullable
     */
  message?: ChangeEmail200Message;
};
