/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangePassword200User } from './changePassword200User';

export type ChangePassword200 = {
  /**
     * New session token if other sessions were revoked
     * @nullable
     */
  token?: string | null;
  user: ChangePassword200User;
};
