/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProject201TwoData } from './createProject201TwoData';
import type { CreateProject201TwoMeta } from './createProject201TwoMeta';

export type CreateProject201Two = {
  data: CreateProject201TwoData;
  meta: CreateProject201TwoMeta;
};
