/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication200OneDataAttachmentsItem } from './createApplication200OneDataAttachmentsItem';
import type { CreateApplication200OneDataItemsItem } from './createApplication200OneDataItemsItem';
import type { CreateApplication200OneDataMetadata } from './createApplication200OneDataMetadata';

export type CreateApplication200OneData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: CreateApplication200OneDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: CreateApplication200OneDataAttachmentsItem[];
  items: CreateApplication200OneDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
