/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist200TwoDataItemsItem } from './createChecklist200TwoDataItemsItem';
import type { CreateChecklist200TwoDataMetadata } from './createChecklist200TwoDataMetadata';
import type { CreateChecklist200TwoDataOptionsItem } from './createChecklist200TwoDataOptionsItem';

export type CreateChecklist200TwoData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: CreateChecklist200TwoDataOptionsItem[];
  items: CreateChecklist200TwoDataItemsItem[];
  metadata: CreateChecklist200TwoDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
