/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication200TwoDataAttachmentsItem } from './createApplication200TwoDataAttachmentsItem';
import type { CreateApplication200TwoDataItemsItem } from './createApplication200TwoDataItemsItem';
import type { CreateApplication200TwoDataMetadata } from './createApplication200TwoDataMetadata';

export type CreateApplication200TwoData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: CreateApplication200TwoDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: CreateApplication200TwoDataAttachmentsItem[];
  items: CreateApplication200TwoDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
