/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganizationInvitationBody = {
  /** The email address of the user to invite */
  email: string;
  /** The role(s) to assign to the user. It can be `admin`, `member`, owner. Eg: "member" */
  role: string | string[];
  /** The organization ID to invite the user to */
  organizationId?: string;
  /** Resend the invitation email, if the user is already invited. Eg: true */
  resend?: boolean;
  teamId?: string | string[];
};
