/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication200ThreeDataAttachmentsItem } from './createApplication200ThreeDataAttachmentsItem';
import type { CreateApplication200ThreeDataItemsItem } from './createApplication200ThreeDataItemsItem';
import type { CreateApplication200ThreeDataMetadata } from './createApplication200ThreeDataMetadata';

export type CreateApplication200ThreeData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: CreateApplication200ThreeDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: CreateApplication200ThreeDataAttachmentsItem[];
  items: CreateApplication200ThreeDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
