/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTag201OneData } from './createTag201OneData';
import type { CreateTag201OneMeta } from './createTag201OneMeta';

export type CreateTag201One = {
  data: CreateTag201OneData;
  meta: CreateTag201OneMeta;
};
