/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist201OneDataItemsItem } from './createChecklist201OneDataItemsItem';
import type { CreateChecklist201OneDataMetadata } from './createChecklist201OneDataMetadata';
import type { CreateChecklist201OneDataOptionsItem } from './createChecklist201OneDataOptionsItem';

export type CreateChecklist201OneData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: CreateChecklist201OneDataOptionsItem[];
  items: CreateChecklist201OneDataItemsItem[];
  metadata: CreateChecklist201OneDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
