/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist200ThreeData } from './createChecklist200ThreeData';
import type { CreateChecklist200ThreeMeta } from './createChecklist200ThreeMeta';

export type CreateChecklist200Three = {
  data: CreateChecklist200ThreeData;
  meta: CreateChecklist200ThreeMeta;
};
