/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication200TwoData } from './createApplication200TwoData';
import type { CreateApplication200TwoMeta } from './createApplication200TwoMeta';

export type CreateApplication200Two = {
  data: CreateApplication200TwoData;
  meta: CreateApplication200TwoMeta;
};
