/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist200ThreeDataItemsItem } from './createChecklist200ThreeDataItemsItem';
import type { CreateChecklist200ThreeDataMetadata } from './createChecklist200ThreeDataMetadata';
import type { CreateChecklist200ThreeDataOptionsItem } from './createChecklist200ThreeDataOptionsItem';

export type CreateChecklist200ThreeData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: CreateChecklist200ThreeDataOptionsItem[];
  items: CreateChecklist200ThreeDataItemsItem[];
  metadata: CreateChecklist200ThreeDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
