/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication201TwoData } from './createApplication201TwoData';
import type { CreateApplication201TwoMeta } from './createApplication201TwoMeta';

export type CreateApplication201Two = {
  data: CreateApplication201TwoData;
  meta: CreateApplication201TwoMeta;
};
