/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication201TwoDataAttachmentsItem } from './createApplication201TwoDataAttachmentsItem';
import type { CreateApplication201TwoDataItemsItem } from './createApplication201TwoDataItemsItem';
import type { CreateApplication201TwoDataMetadata } from './createApplication201TwoDataMetadata';

export type CreateApplication201TwoData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: CreateApplication201TwoDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: CreateApplication201TwoDataAttachmentsItem[];
  items: CreateApplication201TwoDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
