/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication200ThreeData } from './createApplication200ThreeData';
import type { CreateApplication200ThreeMeta } from './createApplication200ThreeMeta';

export type CreateApplication200Three = {
  data: CreateApplication200ThreeData;
  meta: CreateApplication200ThreeMeta;
};
