/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplicationBodyTwoAttachmentsItem } from './createApplicationBodyTwoAttachmentsItem';
import type { CreateApplicationBodyTwoItemsItem } from './createApplicationBodyTwoItemsItem';
import type { CreateApplicationBodyTwoMetadata } from './createApplicationBodyTwoMetadata';

export type CreateApplicationBodyTwo = {
  id?: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status?: 'draft' | 'completed';
  transcript?: string | null;
  gallerySourceApplicationId?: string | null;
  metadata?: CreateApplicationBodyTwoMetadata;
  items?: CreateApplicationBodyTwoItemsItem[];
  attachments?: CreateApplicationBodyTwoAttachmentsItem[];
};
