/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProject201OneData } from './createProject201OneData';
import type { CreateProject201OneMeta } from './createProject201OneMeta';

export type CreateProject201One = {
  data: CreateProject201OneData;
  meta: CreateProject201OneMeta;
};
