/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist201ThreeData } from './createChecklist201ThreeData';
import type { CreateChecklist201ThreeMeta } from './createChecklist201ThreeMeta';

export type CreateChecklist201Three = {
  data: CreateChecklist201ThreeData;
  meta: CreateChecklist201ThreeMeta;
};
