/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTag200TwoData } from './createTag200TwoData';
import type { CreateTag200TwoMeta } from './createTag200TwoMeta';

export type CreateTag200Two = {
  data: CreateTag200TwoData;
  meta: CreateTag200TwoMeta;
};
