/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist200OneDataItemsItem } from './createChecklist200OneDataItemsItem';
import type { CreateChecklist200OneDataMetadata } from './createChecklist200OneDataMetadata';
import type { CreateChecklist200OneDataOptionsItem } from './createChecklist200OneDataOptionsItem';

export type CreateChecklist200OneData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: CreateChecklist200OneDataOptionsItem[];
  items: CreateChecklist200OneDataItemsItem[];
  metadata: CreateChecklist200OneDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
