/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTag201TwoData } from './createTag201TwoData';
import type { CreateTag201TwoMeta } from './createTag201TwoMeta';

export type CreateTag201Two = {
  data: CreateTag201TwoData;
  meta: CreateTag201TwoMeta;
};
