/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication201ThreeData } from './createApplication201ThreeData';
import type { CreateApplication201ThreeMeta } from './createApplication201ThreeMeta';

export type CreateApplication201Three = {
  data: CreateApplication201ThreeData;
  meta: CreateApplication201ThreeMeta;
};
