/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProject200TwoData } from './createProject200TwoData';
import type { CreateProject200TwoMeta } from './createProject200TwoMeta';

export type CreateProject200Two = {
  data: CreateProject200TwoData;
  meta: CreateProject200TwoMeta;
};
