/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplicationBodyThreeAttachmentsItem } from './createApplicationBodyThreeAttachmentsItem';
import type { CreateApplicationBodyThreeItemsItem } from './createApplicationBodyThreeItemsItem';
import type { CreateApplicationBodyThreeMetadata } from './createApplicationBodyThreeMetadata';

export type CreateApplicationBodyThree = {
  id?: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status?: 'draft' | 'completed';
  transcript?: string | null;
  gallerySourceApplicationId?: string | null;
  metadata?: CreateApplicationBodyThreeMetadata;
  items?: CreateApplicationBodyThreeItemsItem[];
  attachments?: CreateApplicationBodyThreeAttachmentsItem[];
};
