/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist200OneData } from './createChecklist200OneData';
import type { CreateChecklist200OneMeta } from './createChecklist200OneMeta';

export type CreateChecklist200One = {
  data: CreateChecklist200OneData;
  meta: CreateChecklist200OneMeta;
};
