/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist201TwoDataItemsItem } from './createChecklist201TwoDataItemsItem';
import type { CreateChecklist201TwoDataMetadata } from './createChecklist201TwoDataMetadata';
import type { CreateChecklist201TwoDataOptionsItem } from './createChecklist201TwoDataOptionsItem';

export type CreateChecklist201TwoData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: CreateChecklist201TwoDataOptionsItem[];
  items: CreateChecklist201TwoDataItemsItem[];
  metadata: CreateChecklist201TwoDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
