/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTag200ThreeData } from './createTag200ThreeData';
import type { CreateTag200ThreeMeta } from './createTag200ThreeMeta';

export type CreateTag200Three = {
  data: CreateTag200ThreeData;
  meta: CreateTag200ThreeMeta;
};
