/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProject201ThreeData } from './createProject201ThreeData';
import type { CreateProject201ThreeMeta } from './createProject201ThreeMeta';

export type CreateProject201Three = {
  data: CreateProject201ThreeData;
  meta: CreateProject201ThreeMeta;
};
