/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklistBodyTwoItemsItem } from './createChecklistBodyTwoItemsItem';
import type { CreateChecklistBodyTwoMetadata } from './createChecklistBodyTwoMetadata';
import type { CreateChecklistBodyTwoOptionsItem } from './createChecklistBodyTwoOptionsItem';

export type CreateChecklistBodyTwo = {
  id?: string;
  title: string;
  source?: string | null;
  tagsIds?: string[];
  options?: CreateChecklistBodyTwoOptionsItem[];
  items?: CreateChecklistBodyTwoItemsItem[];
  metadata?: CreateChecklistBodyTwoMetadata;
};
