/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication201OneData } from './createApplication201OneData';
import type { CreateApplication201OneMeta } from './createApplication201OneMeta';

export type CreateApplication201One = {
  data: CreateApplication201OneData;
  meta: CreateApplication201OneMeta;
};
