/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication201ThreeDataAttachmentsItem } from './createApplication201ThreeDataAttachmentsItem';
import type { CreateApplication201ThreeDataItemsItem } from './createApplication201ThreeDataItemsItem';
import type { CreateApplication201ThreeDataMetadata } from './createApplication201ThreeDataMetadata';

export type CreateApplication201ThreeData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: CreateApplication201ThreeDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: CreateApplication201ThreeDataAttachmentsItem[];
  items: CreateApplication201ThreeDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
