/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTag200OneData } from './createTag200OneData';
import type { CreateTag200OneMeta } from './createTag200OneMeta';

export type CreateTag200One = {
  data: CreateTag200OneData;
  meta: CreateTag200OneMeta;
};
