/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication200OneData } from './createApplication200OneData';
import type { CreateApplication200OneMeta } from './createApplication200OneMeta';

export type CreateApplication200One = {
  data: CreateApplication200OneData;
  meta: CreateApplication200OneMeta;
};
