/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProject200OneData } from './createProject200OneData';
import type { CreateProject200OneMeta } from './createProject200OneMeta';

export type CreateProject200One = {
  data: CreateProject200OneData;
  meta: CreateProject200OneMeta;
};
