/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProject200ThreeData } from './createProject200ThreeData';
import type { CreateProject200ThreeMeta } from './createProject200ThreeMeta';

export type CreateProject200Three = {
  data: CreateProject200ThreeData;
  meta: CreateProject200ThreeMeta;
};
