/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateApplication201OneDataAttachmentsItem } from './createApplication201OneDataAttachmentsItem';
import type { CreateApplication201OneDataItemsItem } from './createApplication201OneDataItemsItem';
import type { CreateApplication201OneDataMetadata } from './createApplication201OneDataMetadata';

export type CreateApplication201OneData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: CreateApplication201OneDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: CreateApplication201OneDataAttachmentsItem[];
  items: CreateApplication201OneDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
