/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist201TwoData } from './createChecklist201TwoData';
import type { CreateChecklist201TwoMeta } from './createChecklist201TwoMeta';

export type CreateChecklist201Two = {
  data: CreateChecklist201TwoData;
  meta: CreateChecklist201TwoMeta;
};
