/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist201ThreeDataItemsItem } from './createChecklist201ThreeDataItemsItem';
import type { CreateChecklist201ThreeDataMetadata } from './createChecklist201ThreeDataMetadata';
import type { CreateChecklist201ThreeDataOptionsItem } from './createChecklist201ThreeDataOptionsItem';

export type CreateChecklist201ThreeData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: CreateChecklist201ThreeDataOptionsItem[];
  items: CreateChecklist201ThreeDataItemsItem[];
  metadata: CreateChecklist201ThreeDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
