/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateChecklist200TwoData } from './createChecklist200TwoData';
import type { CreateChecklist200TwoMeta } from './createChecklist200TwoMeta';

export type CreateChecklist200Two = {
  data: CreateChecklist200TwoData;
  meta: CreateChecklist200TwoMeta;
};
