/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteAttachment200ThreeData } from './deleteAttachment200ThreeData';
import type { DeleteAttachment200ThreeMeta } from './deleteAttachment200ThreeMeta';

export type DeleteAttachment200Three = {
  data: DeleteAttachment200ThreeData;
  meta: DeleteAttachment200ThreeMeta;
};
