/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status message of the deletion process
 */
export type DeleteUser200Message = typeof DeleteUser200Message[keyof typeof DeleteUser200Message];


export const DeleteUser200Message = {
  User_deleted: 'User deleted',
  Verification_email_sent: 'Verification email sent',
} as const;
