/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteChecklist200ThreeData } from './deleteChecklist200ThreeData';
import type { DeleteChecklist200ThreeMeta } from './deleteChecklist200ThreeMeta';

export type DeleteChecklist200Three = {
  data: DeleteChecklist200ThreeData;
  meta: DeleteChecklist200ThreeMeta;
};
