/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteAttachment200OneData } from './deleteAttachment200OneData';
import type { DeleteAttachment200OneMeta } from './deleteAttachment200OneMeta';

export type DeleteAttachment200One = {
  data: DeleteAttachment200OneData;
  meta: DeleteAttachment200OneMeta;
};
