/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApplication200TwoData } from './deleteApplication200TwoData';
import type { DeleteApplication200TwoMeta } from './deleteApplication200TwoMeta';

export type DeleteApplication200Two = {
  data: DeleteApplication200TwoData;
  meta: DeleteApplication200TwoMeta;
};
