/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteAttachment200TwoData } from './deleteAttachment200TwoData';
import type { DeleteAttachment200TwoMeta } from './deleteAttachment200TwoMeta';

export type DeleteAttachment200Two = {
  data: DeleteAttachment200TwoData;
  meta: DeleteAttachment200TwoMeta;
};
