/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApplication200ThreeData } from './deleteApplication200ThreeData';
import type { DeleteApplication200ThreeMeta } from './deleteApplication200ThreeMeta';

export type DeleteApplication200Three = {
  data: DeleteApplication200ThreeData;
  meta: DeleteApplication200ThreeMeta;
};
