/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteProject200TwoData } from './deleteProject200TwoData';
import type { DeleteProject200TwoMeta } from './deleteProject200TwoMeta';

export type DeleteProject200Two = {
  data: DeleteProject200TwoData;
  meta: DeleteProject200TwoMeta;
};
