/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteProject200OneData } from './deleteProject200OneData';
import type { DeleteProject200OneMeta } from './deleteProject200OneMeta';

export type DeleteProject200One = {
  data: DeleteProject200OneData;
  meta: DeleteProject200OneMeta;
};
