/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteUser200Message } from './deleteUser200Message';

export type DeleteUser200 = {
  /** Indicates if the operation was successful */
  success: boolean;
  /** Status message of the deletion process */
  message: DeleteUser200Message;
};
