/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type DeleteUserBody = {
  /** The callback URL to redirect to after the user is deleted */
  callbackURL?: string;
  /** The user's password. Required if session is not fresh */
  password?: string;
  /** The deletion verification token */
  token?: string;
};
