/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApplication200OneData } from './deleteApplication200OneData';
import type { DeleteApplication200OneMeta } from './deleteApplication200OneMeta';

export type DeleteApplication200One = {
  data: DeleteApplication200OneData;
  meta: DeleteApplication200OneMeta;
};
