/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteProject200ThreeData } from './deleteProject200ThreeData';
import type { DeleteProject200ThreeMeta } from './deleteProject200ThreeMeta';

export type DeleteProject200Three = {
  data: DeleteProject200ThreeData;
  meta: DeleteProject200ThreeMeta;
};
