/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplication200OneData } from './getApplication200OneData';
import type { GetApplication200OneMeta } from './getApplication200OneMeta';

export type GetApplication200One = {
  data: GetApplication200OneData;
  meta: GetApplication200OneMeta;
};
