/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiAuthOrganizationListUserInvitations200Item = {
  id: string;
  email: string;
  role: string;
  organizationId: string;
  organizationName: string;
  /** The ID of the user who created the invitation */
  inviterId: string;
  /**
     * The ID of the team associated with the invitation
     * @nullable
     */
  teamId?: string | null;
  status: string;
  expiresAt: string;
  createdAt: string;
};
