/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplication200TwoData } from './getApplication200TwoData';
import type { GetApplication200TwoMeta } from './getApplication200TwoMeta';

export type GetApplication200Two = {
  data: GetApplication200TwoData;
  meta: GetApplication200TwoMeta;
};
