/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplication200TwoDataItemsItemAttachmentsItem } from './getApplication200TwoDataItemsItemAttachmentsItem';
import type { GetApplication200TwoDataItemsItemMetadata } from './getApplication200TwoDataItemsItemMetadata';

export type GetApplication200TwoDataItemsItem = {
  id: string;
  position: number;
  checklistItemId: string | null;
  parentId: string | null;
  title: string;
  description: string;
  tagsIds: string[];
  answer: string;
  answeredAt: string | null;
  note: string;
  quantity: number | null;
  suggested: boolean;
  suggestionSource: string | null;
  workflowStatus: string | null;
  metadata: GetApplication200TwoDataItemsItemMetadata;
  attachments: GetApplication200TwoDataItemsItemAttachmentsItem[];
  createdAt: string;
  updatedAt: string;
};
