/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplication200ThreeDataAttachmentsItem } from './getApplication200ThreeDataAttachmentsItem';
import type { GetApplication200ThreeDataItemsItem } from './getApplication200ThreeDataItemsItem';
import type { GetApplication200ThreeDataMetadata } from './getApplication200ThreeDataMetadata';

export type GetApplication200ThreeData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: GetApplication200ThreeDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: GetApplication200ThreeDataAttachmentsItem[];
  items: GetApplication200ThreeDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
