/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAuthAccountInfo200Account } from './getApiAuthAccountInfo200Account';
import type { GetApiAuthAccountInfo200Data } from './getApiAuthAccountInfo200Data';
import type { GetApiAuthAccountInfo200User } from './getApiAuthAccountInfo200User';

export type GetApiAuthAccountInfo200 = {
  user: GetApiAuthAccountInfo200User;
  account: GetApiAuthAccountInfo200Account;
  data: GetApiAuthAccountInfo200Data;
};
