/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplication200ThreeData } from './getApplication200ThreeData';
import type { GetApplication200ThreeMeta } from './getApplication200ThreeMeta';

export type GetApplication200Three = {
  data: GetApplication200ThreeData;
  meta: GetApplication200ThreeMeta;
};
