/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplication200TwoDataAttachmentsItem } from './getApplication200TwoDataAttachmentsItem';
import type { GetApplication200TwoDataItemsItem } from './getApplication200TwoDataItemsItem';
import type { GetApplication200TwoDataMetadata } from './getApplication200TwoDataMetadata';

export type GetApplication200TwoData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: GetApplication200TwoDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: GetApplication200TwoDataAttachmentsItem[];
  items: GetApplication200TwoDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
