/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Confirmation message
 */
export type GetApiAuthDeleteUserCallback200Message = typeof GetApiAuthDeleteUserCallback200Message[keyof typeof GetApiAuthDeleteUserCallback200Message];


export const GetApiAuthDeleteUserCallback200Message = {
  User_deleted: 'User deleted',
} as const;
