/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApplication200OneDataAttachmentsItem } from './getApplication200OneDataAttachmentsItem';
import type { GetApplication200OneDataItemsItem } from './getApplication200OneDataItemsItem';
import type { GetApplication200OneDataMetadata } from './getApplication200OneDataMetadata';

export type GetApplication200OneData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: GetApplication200OneDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: GetApplication200OneDataAttachmentsItem[];
  items: GetApplication200OneDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
