/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemAttachmentsItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemAttachmentsItem';
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemItemsItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemItemsItem';
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemMetadata } from './getByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemMetadata';

export type GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItem = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemAttachmentsItem[];
  items: GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeDataItemApplicationsItemItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
