/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200OneDataItem';
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200OneMeta } from './getByOrgIdProjectsByProjectIdApplicationGroups200OneMeta';

export type GetByOrgIdProjectsByProjectIdApplicationGroups200One = {
  data: GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItem[];
  meta: GetByOrgIdProjectsByProjectIdApplicationGroups200OneMeta;
};
