/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeMetaPagination } from './getByOrgIdProjectsByProjectIdApplicationGroups200ThreeMetaPagination';

export type GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeMeta = {
  pagination: GetByOrgIdProjectsByProjectIdApplicationGroups200ThreeMetaPagination;
};
