/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemAttachmentsItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemAttachmentsItem';
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemItemsItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemItemsItem';
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemMetadata } from './getByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemMetadata';

export type GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItem = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemAttachmentsItem[];
  items: GetByOrgIdProjectsByProjectIdApplicationGroups200OneDataItemApplicationsItemItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
