/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemAttachmentsItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemAttachmentsItem';
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemItemsItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemItemsItem';
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemMetadata } from './getByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemMetadata';

export type GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItem = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemAttachmentsItem[];
  items: GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItemItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
