/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItem } from './getByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItem';

export type GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItem = {
  tagsIds: string[];
  applicationsCount: number;
  applications: GetByOrgIdProjectsByProjectIdApplicationGroups200TwoDataItemApplicationsItem[];
};
