/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetChecklist200OneData } from './getChecklist200OneData';
import type { GetChecklist200OneMeta } from './getChecklist200OneMeta';

export type GetChecklist200One = {
  data: GetChecklist200OneData;
  meta: GetChecklist200OneMeta;
};
