/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetChecklist200ThreeData } from './getChecklist200ThreeData';
import type { GetChecklist200ThreeMeta } from './getChecklist200ThreeMeta';

export type GetChecklist200Three = {
  data: GetChecklist200ThreeData;
  meta: GetChecklist200ThreeMeta;
};
