/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetChecklist200ThreeDataItemsItem } from './getChecklist200ThreeDataItemsItem';
import type { GetChecklist200ThreeDataMetadata } from './getChecklist200ThreeDataMetadata';
import type { GetChecklist200ThreeDataOptionsItem } from './getChecklist200ThreeDataOptionsItem';

export type GetChecklist200ThreeData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: GetChecklist200ThreeDataOptionsItem[];
  items: GetChecklist200ThreeDataItemsItem[];
  metadata: GetChecklist200ThreeDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
