/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetChecklist200TwoDataItemsItem } from './getChecklist200TwoDataItemsItem';
import type { GetChecklist200TwoDataMetadata } from './getChecklist200TwoDataMetadata';
import type { GetChecklist200TwoDataOptionsItem } from './getChecklist200TwoDataOptionsItem';

export type GetChecklist200TwoData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: GetChecklist200TwoDataOptionsItem[];
  items: GetChecklist200TwoDataItemsItem[];
  metadata: GetChecklist200TwoDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
