/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetChecklist200OneDataItemsItem } from './getChecklist200OneDataItemsItem';
import type { GetChecklist200OneDataMetadata } from './getChecklist200OneDataMetadata';
import type { GetChecklist200OneDataOptionsItem } from './getChecklist200OneDataOptionsItem';

export type GetChecklist200OneData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: GetChecklist200OneDataOptionsItem[];
  items: GetChecklist200OneDataItemsItem[];
  metadata: GetChecklist200OneDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
