/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetProject200OneData } from './getProject200OneData';
import type { GetProject200OneMeta } from './getProject200OneMeta';

export type GetProject200One = {
  data: GetProject200OneData;
  meta: GetProject200OneMeta;
};
