/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetProject200TwoData } from './getProject200TwoData';
import type { GetProject200TwoMeta } from './getProject200TwoMeta';

export type GetProject200Two = {
  data: GetProject200TwoData;
  meta: GetProject200TwoMeta;
};
