/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetReportTags200TwoDataApplicationProgress } from './getReportTags200TwoDataApplicationProgress';
import type { GetReportTags200TwoDataItemProgress } from './getReportTags200TwoDataItemProgress';
import type { GetReportTags200TwoDataPendingGroupsItem } from './getReportTags200TwoDataPendingGroupsItem';

export type GetReportTags200TwoData = {
  itemProgress: GetReportTags200TwoDataItemProgress;
  applicationProgress: GetReportTags200TwoDataApplicationProgress;
  pendingGroups: GetReportTags200TwoDataPendingGroupsItem[];
};
