/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetReportTags200OneDataApplicationProgress } from './getReportTags200OneDataApplicationProgress';
import type { GetReportTags200OneDataItemProgress } from './getReportTags200OneDataItemProgress';
import type { GetReportTags200OneDataPendingGroupsItem } from './getReportTags200OneDataPendingGroupsItem';

export type GetReportTags200OneData = {
  itemProgress: GetReportTags200OneDataItemProgress;
  applicationProgress: GetReportTags200OneDataApplicationProgress;
  pendingGroups: GetReportTags200OneDataPendingGroupsItem[];
};
