/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetReportTags200ThreeData } from './getReportTags200ThreeData';
import type { GetReportTags200ThreeMeta } from './getReportTags200ThreeMeta';

export type GetReportTags200Three = {
  data: GetReportTags200ThreeData;
  meta: GetReportTags200ThreeMeta;
};
