/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetReportTags200TwoData } from './getReportTags200TwoData';
import type { GetReportTags200TwoMeta } from './getReportTags200TwoMeta';

export type GetReportTags200Two = {
  data: GetReportTags200TwoData;
  meta: GetReportTags200TwoMeta;
};
