/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetReportTags200TwoDataPendingGroupsItemApplication } from './getReportTags200TwoDataPendingGroupsItemApplication';
import type { GetReportTags200TwoDataPendingGroupsItemItemsItem } from './getReportTags200TwoDataPendingGroupsItemItemsItem';

export type GetReportTags200TwoDataPendingGroupsItem = {
  application: GetReportTags200TwoDataPendingGroupsItemApplication;
  items: GetReportTags200TwoDataPendingGroupsItemItemsItem[];
};
