/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetReportTags200ThreeDataApplicationProgress } from './getReportTags200ThreeDataApplicationProgress';
import type { GetReportTags200ThreeDataItemProgress } from './getReportTags200ThreeDataItemProgress';
import type { GetReportTags200ThreeDataPendingGroupsItem } from './getReportTags200ThreeDataPendingGroupsItem';

export type GetReportTags200ThreeData = {
  itemProgress: GetReportTags200ThreeDataItemProgress;
  applicationProgress: GetReportTags200ThreeDataApplicationProgress;
  pendingGroups: GetReportTags200ThreeDataPendingGroupsItem[];
};
