/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { GetReportTags200ThreeDataPendingGroupsItemApplication } from './getReportTags200ThreeDataPendingGroupsItemApplication';
import type { GetReportTags200ThreeDataPendingGroupsItemItemsItem } from './getReportTags200ThreeDataPendingGroupsItemItemsItem';

export type GetReportTags200ThreeDataPendingGroupsItem = {
  application: GetReportTags200ThreeDataPendingGroupsItemApplication;
  items: GetReportTags200ThreeDataPendingGroupsItemItemsItem[];
};
