/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { LinkSocialAccountBodyAdditionalData } from './linkSocialAccountBodyAdditionalData';
import type { LinkSocialAccountBodyAdditionalParams } from './linkSocialAccountBodyAdditionalParams';
import type { LinkSocialAccountBodyIdToken } from './linkSocialAccountBodyIdToken';

export type LinkSocialAccountBody = {
  /** The URL to redirect to after the user has signed in */
  callbackURL?: string;
  provider: 'apple' | 'atlassian' | 'cloudflare' | 'cognito' | 'discord' | 'facebook' | 'figma' | 'github' | 'microsoft' | 'google' | 'huggingface' | 'slack' | 'spotify' | 'twitch' | 'twitter' | 'dropbox' | 'kick' | 'linear' | 'linkedin' | 'gitlab' | 'tiktok' | 'reddit' | 'roblox' | 'salesforce' | 'vk' | 'zoom' | 'notion' | 'kakao' | 'naver' | 'line' | 'paybin' | 'paypal' | 'polar' | 'railway' | 'vercel' | 'wechat' | string;
  idToken?: LinkSocialAccountBodyIdToken;
  requestSignUp?: boolean;
  /** Additional scopes to request from the provider */
  scopes?: string[];
  /** The URL to redirect to if there is an error during the link process */
  errorCallbackURL?: string;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: boolean;
  /** The login hint to use for the authorization code request */
  loginHint?: string;
  /** Extra query parameters to append to the provider authorization URL (e.g. Cognito identity_provider, Google hd). */
  additionalParams?: LinkSocialAccountBodyAdditionalParams;
  additionalData?: LinkSocialAccountBodyAdditionalData;
};
