/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type LinkSocialAccount200 = {
  /** The authorization URL to redirect the user to */
  url?: string;
  /** Indicates if the user should be redirected to the authorization URL */
  redirect: boolean;
  status?: boolean;
};
