/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListApplications200OneDataItemAttachmentsItem } from './listApplications200OneDataItemAttachmentsItem';
import type { ListApplications200OneDataItemItemsItem } from './listApplications200OneDataItemItemsItem';
import type { ListApplications200OneDataItemMetadata } from './listApplications200OneDataItemMetadata';

export type ListApplications200OneDataItem = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: ListApplications200OneDataItemMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: ListApplications200OneDataItemAttachmentsItem[];
  items: ListApplications200OneDataItemItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
