/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListChecklists200TwoDataItem } from './listChecklists200TwoDataItem';
import type { ListChecklists200TwoMeta } from './listChecklists200TwoMeta';

export type ListChecklists200Two = {
  data: ListChecklists200TwoDataItem[];
  meta: ListChecklists200TwoMeta;
};
