/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListChecklists200ThreeDataItem } from './listChecklists200ThreeDataItem';
import type { ListChecklists200ThreeMeta } from './listChecklists200ThreeMeta';

export type ListChecklists200Three = {
  data: ListChecklists200ThreeDataItem[];
  meta: ListChecklists200ThreeMeta;
};
