/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListApplications200ThreeDataItemAttachmentsItem } from './listApplications200ThreeDataItemAttachmentsItem';
import type { ListApplications200ThreeDataItemItemsItem } from './listApplications200ThreeDataItemItemsItem';
import type { ListApplications200ThreeDataItemMetadata } from './listApplications200ThreeDataItemMetadata';

export type ListApplications200ThreeDataItem = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: ListApplications200ThreeDataItemMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: ListApplications200ThreeDataItemAttachmentsItem[];
  items: ListApplications200ThreeDataItemItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
