/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListProjects200OneDataItem } from './listProjects200OneDataItem';
import type { ListProjects200OneMeta } from './listProjects200OneMeta';

export type ListProjects200One = {
  data: ListProjects200OneDataItem[];
  meta: ListProjects200OneMeta;
};
