/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListChecklists200ThreeMetaPagination } from './listChecklists200ThreeMetaPagination';

export type ListChecklists200ThreeMeta = {
  pagination: ListChecklists200ThreeMetaPagination;
};
