/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListTags200OneMetaPagination } from './listTags200OneMetaPagination';

export type ListTags200OneMeta = {
  pagination: ListTags200OneMetaPagination;
};
