/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListChecklists200OneDataItemItemsItem } from './listChecklists200OneDataItemItemsItem';
import type { ListChecklists200OneDataItemMetadata } from './listChecklists200OneDataItemMetadata';
import type { ListChecklists200OneDataItemOptionsItem } from './listChecklists200OneDataItemOptionsItem';

export type ListChecklists200OneDataItem = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: ListChecklists200OneDataItemOptionsItem[];
  items: ListChecklists200OneDataItemItemsItem[];
  metadata: ListChecklists200OneDataItemMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
