/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListChecklists200OneDataItem } from './listChecklists200OneDataItem';
import type { ListChecklists200OneMeta } from './listChecklists200OneMeta';

export type ListChecklists200One = {
  data: ListChecklists200OneDataItem[];
  meta: ListChecklists200OneMeta;
};
