/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListChecklists200ThreeDataItemItemsItem } from './listChecklists200ThreeDataItemItemsItem';
import type { ListChecklists200ThreeDataItemMetadata } from './listChecklists200ThreeDataItemMetadata';
import type { ListChecklists200ThreeDataItemOptionsItem } from './listChecklists200ThreeDataItemOptionsItem';

export type ListChecklists200ThreeDataItem = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: ListChecklists200ThreeDataItemOptionsItem[];
  items: ListChecklists200ThreeDataItemItemsItem[];
  metadata: ListChecklists200ThreeDataItemMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
