/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListApplications200TwoDataItemAttachmentsItem } from './listApplications200TwoDataItemAttachmentsItem';
import type { ListApplications200TwoDataItemItemsItem } from './listApplications200TwoDataItemItemsItem';
import type { ListApplications200TwoDataItemMetadata } from './listApplications200TwoDataItemMetadata';

export type ListApplications200TwoDataItem = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: ListApplications200TwoDataItemMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: ListApplications200TwoDataItemAttachmentsItem[];
  items: ListApplications200TwoDataItemItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
