/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListApplications200OneDataItem } from './listApplications200OneDataItem';
import type { ListApplications200OneMeta } from './listApplications200OneMeta';

export type ListApplications200One = {
  data: ListApplications200OneDataItem[];
  meta: ListApplications200OneMeta;
};
