/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListTags200TwoDataItem } from './listTags200TwoDataItem';
import type { ListTags200TwoMeta } from './listTags200TwoMeta';

export type ListTags200Two = {
  data: ListTags200TwoDataItem[];
  meta: ListTags200TwoMeta;
};
