/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListChecklists200TwoDataItemItemsItem } from './listChecklists200TwoDataItemItemsItem';
import type { ListChecklists200TwoDataItemMetadata } from './listChecklists200TwoDataItemMetadata';
import type { ListChecklists200TwoDataItemOptionsItem } from './listChecklists200TwoDataItemOptionsItem';

export type ListChecklists200TwoDataItem = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: ListChecklists200TwoDataItemOptionsItem[];
  items: ListChecklists200TwoDataItemItemsItem[];
  metadata: ListChecklists200TwoDataItemMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
