/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListTags200ThreeMetaPagination } from './listTags200ThreeMetaPagination';

export type ListTags200ThreeMeta = {
  pagination: ListTags200ThreeMetaPagination;
};
