/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListTags200OneDataItem } from './listTags200OneDataItem';
import type { ListTags200OneMeta } from './listTags200OneMeta';

export type ListTags200One = {
  data: ListTags200OneDataItem[];
  meta: ListTags200OneMeta;
};
