/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListApplications200ThreeDataItem } from './listApplications200ThreeDataItem';
import type { ListApplications200ThreeMeta } from './listApplications200ThreeMeta';

export type ListApplications200Three = {
  data: ListApplications200ThreeDataItem[];
  meta: ListApplications200ThreeMeta;
};
