/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ListProjects200TwoDataItem } from './listProjects200TwoDataItem';
import type { ListProjects200TwoMeta } from './listProjects200TwoMeta';

export type ListProjects200Two = {
  data: ListProjects200TwoDataItem[];
  meta: ListProjects200TwoMeta;
};
