/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthOrganizationHasPermissionBodyPermission } from './postApiAuthOrganizationHasPermissionBodyPermission';
import type { PostApiAuthOrganizationHasPermissionBodyPermissions } from './postApiAuthOrganizationHasPermissionBodyPermissions';

export type PostApiAuthOrganizationHasPermissionBody = {
  /**
     * The permission to check
     * @deprecated
     */
  permission?: PostApiAuthOrganizationHasPermissionBodyPermission;
  /** The permission to check */
  permissions: PostApiAuthOrganizationHasPermissionBodyPermissions;
};
