/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthRefreshTokenBody = {
  /** The Better Auth account ID */
  accountId: string;
  /** The user ID associated with the account */
  userId?: string;
} | {
  /** Select the current OAuth account from its signed cookie */
  useAccountCookie: true;
  /** The user ID associated with the account */
  userId?: string;
};
