/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthOrganizationCreateBodyMetadata } from './postApiAuthOrganizationCreateBodyMetadata';

export type PostApiAuthOrganizationCreateBody = {
  /**
     * The name of the organization
     * @minLength 1
     */
  name: string;
  /**
     * The slug of the organization
     * @minLength 1
     */
  slug: string;
  /** The user id of the organization creator. If not provided, the current user will be used. Should only be used by admins or when called by the server. server-only. Eg: "user-id" */
  userId?: string;
  /**
     * The logo of the organization
     * @nullable
     */
  logo?: string | null;
  /** The metadata of the organization */
  metadata?: PostApiAuthOrganizationCreateBodyMetadata;
  /** Whether to keep the current active organization active after creating a new one. Eg: true */
  keepCurrentActiveOrganization?: boolean;
};
