/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthOrganizationRejectInvitation200Invitation } from './postApiAuthOrganizationRejectInvitation200Invitation';
import type { PostApiAuthOrganizationRejectInvitation200Member } from './postApiAuthOrganizationRejectInvitation200Member';

export type PostApiAuthOrganizationRejectInvitation200 = {
  invitation?: PostApiAuthOrganizationRejectInvitation200Invitation;
  /** @nullable */
  member?: PostApiAuthOrganizationRejectInvitation200Member;
};
