/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthOrganizationRemoveMemberBody = {
  /** The ID or email of the member to remove */
  memberIdOrEmail: string;
  /** The ID of the organization to remove the member from. If not provided, the active organization will be used. Eg: "org-id" */
  organizationId?: string;
};
