/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthOrganizationAcceptInvitation200Invitation } from './postApiAuthOrganizationAcceptInvitation200Invitation';
import type { PostApiAuthOrganizationAcceptInvitation200Member } from './postApiAuthOrganizationAcceptInvitation200Member';

export type PostApiAuthOrganizationAcceptInvitation200 = {
  invitation?: PostApiAuthOrganizationAcceptInvitation200Invitation;
  member?: PostApiAuthOrganizationAcceptInvitation200Member;
};
