/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthOrganizationUpdateBodyDataMetadata } from './postApiAuthOrganizationUpdateBodyDataMetadata';

export type PostApiAuthOrganizationUpdateBodyData = {
  /**
     * The name of the organization
     * @minLength 1
     */
  name?: string;
  /**
     * The slug of the organization
     * @minLength 1
     */
  slug?: string;
  /**
     * The logo of the organization
     * @nullable
     */
  logo?: string | null;
  /** The metadata of the organization */
  metadata?: PostApiAuthOrganizationUpdateBodyDataMetadata;
};
