/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PresignUpload200TwoDataItemHeaders } from './presignUpload200TwoDataItemHeaders';

export type PresignUpload200TwoDataItem = {
  key: string;
  uploadUrl: string;
  method: string;
  headers: PresignUpload200TwoDataItemHeaders;
  expiresAt: string;
};
