/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PresignUpload200OneDataItem } from './presignUpload200OneDataItem';
import type { PresignUpload200OneMeta } from './presignUpload200OneMeta';

export type PresignUpload200One = {
  data: PresignUpload200OneDataItem[];
  meta: PresignUpload200OneMeta;
};
