/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { PresignUpload200ThreeDataItem } from './presignUpload200ThreeDataItem';
import type { PresignUpload200ThreeMeta } from './presignUpload200ThreeMeta';

export type PresignUpload200Three = {
  data: PresignUpload200ThreeDataItem[];
  meta: PresignUpload200ThreeMeta;
};
