/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ReportTagsApplicationProgress } from './reportTagsApplicationProgress';
import type { ReportTagsItemProgress } from './reportTagsItemProgress';
import type { ReportTagsPendingGroupsItem } from './reportTagsPendingGroupsItem';

export interface ReportTags {
  itemProgress: ReportTagsItemProgress;
  applicationProgress: ReportTagsApplicationProgress;
  pendingGroups: ReportTagsPendingGroupsItem[];
}
