/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ReportPendingGroupApplication } from './reportPendingGroupApplication';
import type { ReportPendingGroupItemsItem } from './reportPendingGroupItemsItem';

export interface ReportPendingGroup {
  application: ReportPendingGroupApplication;
  items: ReportPendingGroupItemsItem[];
}
