/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { ReportTagsResponseDataApplicationProgress } from './reportTagsResponseDataApplicationProgress';
import type { ReportTagsResponseDataItemProgress } from './reportTagsResponseDataItemProgress';
import type { ReportTagsResponseDataPendingGroupsItem } from './reportTagsResponseDataPendingGroupsItem';

export type ReportTagsResponseData = {
  itemProgress: ReportTagsResponseDataItemProgress;
  applicationProgress: ReportTagsResponseDataApplicationProgress;
  pendingGroups: ReportTagsResponseDataPendingGroupsItem[];
};
