/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type ResetPasswordWithEmailOTPBody = {
  /** Email address to reset the password */
  email: string;
  /** OTP sent to the email */
  otp: string;
  /** New password */
  password: string;
};
