/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type SendVerificationEmailBody = {
  /** The email to send the verification email to */
  email: string;
  /**
     * The URL to use for email verification callback
     * @nullable
     */
  callbackURL?: string | null;
};
