/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type SetActiveOrganizationBody = {
  /**
     * The organization id to set as active. It can be null to unset the active organization. Eg: "org-id"
     * @nullable
     */
  organizationId?: string | null;
  /** The organization slug to set as active. It can be null to unset the active organization if organizationId is not provided. Eg: "org-slug" */
  organizationSlug?: string;
};
