/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

/**
 * Session response when idToken is provided
 */
export type SignInEmail200 = {
  redirect: false;
  /** Session token */
  token: string;
  /** @nullable */
  url?: string | null;
  user: User;
};
