/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type SignInEmailBody = {
  /** Email of the user */
  email: string;
  /** Password of the user */
  password: string;
  /** Callback URL to use as a redirect for email verification */
  callbackURL?: string;
  /** If this is false, the session will not be remembered. Default is `true`. */
  rememberMe?: boolean;
};
