/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type SignUpWithEmailAndPassword200User = {
  /** The unique identifier of the user */
  id: string;
  /** The email address of the user */
  email: string;
  /** The name of the user */
  name: string;
  /**
     * The profile image URL of the user
     * @nullable
     */
  image?: string | null;
  /** Whether the email has been verified */
  emailVerified: boolean;
  /** When the user was created */
  createdAt: string;
  /** When the user was last updated */
  updatedAt: string;
};
