/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type SignInWithEmailOTPBody = {
  /** Email address to sign in */
  email: string;
  /** OTP sent to the email */
  otp: string;
  /** User display name. Only used if the user is registering for the first time. Eg: "my-name" */
  name?: string;
  /** User profile image URL. Only used if the user is registering for the first time. */
  image?: string;
  [key: string]: unknown;
};
