/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type SignUpWithEmailAndPasswordBody = {
  /** The name of the user */
  name: string;
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
  /** The profile image URL of the user */
  image?: string;
  /** The URL to use for email verification callback */
  callbackURL?: string;
  /** If this is false, the session will not be remembered. Default is `true`. */
  rememberMe?: boolean;
};
