/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type SignOutBody = {
  /** The URL to redirect to after provider logout */
  callbackURL?: string;
  /** Return the provider logout URL without redirecting */
  disableRedirect?: boolean;
  /** State to pass to the provider logout endpoint */
  state?: string;
};
