/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { SocialSignInBodyIdTokenUser } from './socialSignInBodyIdTokenUser';

export type SocialSignInBodyIdToken = {
  /** ID token from the provider */
  token: string;
  /** Nonce used to generate the token */
  nonce?: string;
  /** Access token from the provider */
  accessToken?: string;
  /** Refresh token from the provider */
  refreshToken?: string;
  /** Expiry date of the token */
  expiresAt?: number;
  /** The user object from the provider. Only available for some providers like Apple. */
  user?: SocialSignInBodyIdTokenUser;
};
