/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

/**
 * Returns session details when idToken is provided, or an authorize URL otherwise
 */
export type SocialSignIn200 = {
  token?: string;
  user?: User;
  url?: string;
  redirect: boolean;
};
