/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { SocialSignInBodyIdTokenUserName } from './socialSignInBodyIdTokenUserName';

/**
 * The user object from the provider. Only available for some providers like Apple.
 */
export type SocialSignInBodyIdTokenUser = {
  name?: SocialSignInBodyIdTokenUserName;
  email?: string;
};
