/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Extra query parameters to append to the provider authorization URL (e.g. Cognito identity_provider, Google hd).
 */
export type SocialSignInBodyAdditionalParams = {[key: string]: string};
