/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { SocialSignInBodyAdditionalData } from './socialSignInBodyAdditionalData';
import type { SocialSignInBodyAdditionalParams } from './socialSignInBodyAdditionalParams';
import type { SocialSignInBodyIdToken } from './socialSignInBodyIdToken';

export type SocialSignInBody = {
  /** Callback URL to redirect to after the user has signed in */
  callbackURL?: string;
  newUserCallbackURL?: string;
  /** Callback URL to redirect to if an error happens */
  errorCallbackURL?: string;
  provider: 'apple' | 'atlassian' | 'cloudflare' | 'cognito' | 'discord' | 'facebook' | 'figma' | 'github' | 'microsoft' | 'google' | 'huggingface' | 'slack' | 'spotify' | 'twitch' | 'twitter' | 'dropbox' | 'kick' | 'linear' | 'linkedin' | 'gitlab' | 'tiktok' | 'reddit' | 'roblox' | 'salesforce' | 'vk' | 'zoom' | 'notion' | 'kakao' | 'naver' | 'line' | 'paybin' | 'paypal' | 'polar' | 'railway' | 'vercel' | 'wechat' | string;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: boolean;
  idToken?: SocialSignInBodyIdToken;
  /** Array of scopes to request from the provider. This will override the default scopes passed. */
  scopes?: string[];
  /** Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider */
  requestSignUp?: boolean;
  /** The login hint to use for the authorization code request */
  loginHint?: string;
  /** Extra query parameters to append to the provider authorization URL (e.g. Cognito identity_provider, Google hd). */
  additionalParams?: SocialSignInBodyAdditionalParams;
  additionalData?: SocialSignInBodyAdditionalData;
};
