/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAttachment200ThreeData } from './updateAttachment200ThreeData';
import type { UpdateAttachment200ThreeMeta } from './updateAttachment200ThreeMeta';

export type UpdateAttachment200Three = {
  data: UpdateAttachment200ThreeData;
  meta: UpdateAttachment200ThreeMeta;
};
