/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklistBodyTwoItemsItem } from './updateChecklistBodyTwoItemsItem';
import type { UpdateChecklistBodyTwoMetadata } from './updateChecklistBodyTwoMetadata';
import type { UpdateChecklistBodyTwoOptionsItem } from './updateChecklistBodyTwoOptionsItem';

export type UpdateChecklistBodyTwo = {
  id?: string;
  title: string;
  source?: string | null;
  tagsIds?: string[];
  options?: UpdateChecklistBodyTwoOptionsItem[];
  items?: UpdateChecklistBodyTwoItemsItem[];
  metadata?: UpdateChecklistBodyTwoMetadata;
};
