/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplicationItem200TwoData } from './updateApplicationItem200TwoData';
import type { UpdateApplicationItem200TwoMeta } from './updateApplicationItem200TwoMeta';

export type UpdateApplicationItem200Two = {
  data: UpdateApplicationItem200TwoData;
  meta: UpdateApplicationItem200TwoMeta;
};
