/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplication200TwoData } from './updateApplication200TwoData';
import type { UpdateApplication200TwoMeta } from './updateApplication200TwoMeta';

export type UpdateApplication200Two = {
  data: UpdateApplication200TwoData;
  meta: UpdateApplication200TwoMeta;
};
