/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplicationItem200ThreeData } from './updateApplicationItem200ThreeData';
import type { UpdateApplicationItem200ThreeMeta } from './updateApplicationItem200ThreeMeta';

export type UpdateApplicationItem200Three = {
  data: UpdateApplicationItem200ThreeData;
  meta: UpdateApplicationItem200ThreeMeta;
};
