/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklistBodyOneItemsItem } from './updateChecklistBodyOneItemsItem';
import type { UpdateChecklistBodyOneMetadata } from './updateChecklistBodyOneMetadata';
import type { UpdateChecklistBodyOneOptionsItem } from './updateChecklistBodyOneOptionsItem';

export type UpdateChecklistBodyOne = {
  id?: string;
  title: string;
  source?: string | null;
  tagsIds?: string[];
  options?: UpdateChecklistBodyOneOptionsItem[];
  items?: UpdateChecklistBodyOneItemsItem[];
  metadata?: UpdateChecklistBodyOneMetadata;
};
