/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplicationItem200OneData } from './updateApplicationItem200OneData';
import type { UpdateApplicationItem200OneMeta } from './updateApplicationItem200OneMeta';

export type UpdateApplicationItem200One = {
  data: UpdateApplicationItem200OneData;
  meta: UpdateApplicationItem200OneMeta;
};
