/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklist200TwoData } from './updateChecklist200TwoData';
import type { UpdateChecklist200TwoMeta } from './updateChecklist200TwoMeta';

export type UpdateChecklist200Two = {
  data: UpdateChecklist200TwoData;
  meta: UpdateChecklist200TwoMeta;
};
