/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateApplicationItem200OneData = {
  id: string;
  position: number;
  checklistItemId: string | null;
  parentId: string | null;
  title: string;
  description: string;
  tagsIds: string[];
  answer: string;
  answeredAt: string | null;
  note: string;
  quantity: number | null;
  suggested: boolean;
  suggestionSource: string | null;
  workflowStatus: string | null;
  metadata: { [key: string]: unknown };
  attachments: ({
  id: string;
  applicationId: string;
  itemId: string | null;
  position: number;
  name: string;
  storageKey: string | null;
  uploadStatus: string;
  url: string | null;
  sizeBytes: number | null;
  checksum: string | null;
  mimeType: string | null;
  width: number | null;
  height: number | null;
  metadata: { [key: string]: unknown };
  createdAt: string;
  updatedAt: string;
})[];
  createdAt: string;
  updatedAt: string;
} | ({
  id: string;
  position: number;
  checklistItemId: string | null;
  parentId: string | null;
  title: string;
  description: string;
  tagsIds: string[];
  answer: string;
  answeredAt: string | null;
  note: string;
  quantity: number | null;
  suggested: boolean;
  suggestionSource: string | null;
  workflowStatus: string | null;
  metadata: { [key: string]: unknown };
  attachments: ({
  id: string;
  applicationId: string;
  itemId: string | null;
  position: number;
  name: string;
  storageKey: string | null;
  uploadStatus: string;
  url: string | null;
  sizeBytes: number | null;
  checksum: string | null;
  mimeType: string | null;
  width: number | null;
  height: number | null;
  metadata: { [key: string]: unknown };
  createdAt: string;
  updatedAt: string;
})[];
  createdAt: string;
  updatedAt: string;
})[];
