/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklist200TwoDataItemsItem } from './updateChecklist200TwoDataItemsItem';
import type { UpdateChecklist200TwoDataMetadata } from './updateChecklist200TwoDataMetadata';
import type { UpdateChecklist200TwoDataOptionsItem } from './updateChecklist200TwoDataOptionsItem';

export type UpdateChecklist200TwoData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: UpdateChecklist200TwoDataOptionsItem[];
  items: UpdateChecklist200TwoDataItemsItem[];
  metadata: UpdateChecklist200TwoDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
