/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplication200ThreeDataAttachmentsItem } from './updateApplication200ThreeDataAttachmentsItem';
import type { UpdateApplication200ThreeDataItemsItem } from './updateApplication200ThreeDataItemsItem';
import type { UpdateApplication200ThreeDataMetadata } from './updateApplication200ThreeDataMetadata';

export type UpdateApplication200ThreeData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: UpdateApplication200ThreeDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: UpdateApplication200ThreeDataAttachmentsItem[];
  items: UpdateApplication200ThreeDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
