/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplication200OneDataItemsItemAttachmentsItemMetadata } from './updateApplication200OneDataItemsItemAttachmentsItemMetadata';

export type UpdateApplication200OneDataItemsItemAttachmentsItem = {
  id: string;
  applicationId: string;
  itemId: string | null;
  position: number;
  name: string;
  storageKey: string | null;
  uploadStatus: string;
  url: string | null;
  sizeBytes: number | null;
  checksum: string | null;
  mimeType: string | null;
  width: number | null;
  height: number | null;
  metadata: UpdateApplication200OneDataItemsItemAttachmentsItemMetadata;
  createdAt: string;
  updatedAt: string;
};
