/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklistBodyThreeItemsItem } from './updateChecklistBodyThreeItemsItem';
import type { UpdateChecklistBodyThreeMetadata } from './updateChecklistBodyThreeMetadata';
import type { UpdateChecklistBodyThreeOptionsItem } from './updateChecklistBodyThreeOptionsItem';

export type UpdateChecklistBodyThree = {
  id?: string;
  title: string;
  source?: string | null;
  tagsIds?: string[];
  options?: UpdateChecklistBodyThreeOptionsItem[];
  items?: UpdateChecklistBodyThreeItemsItem[];
  metadata?: UpdateChecklistBodyThreeMetadata;
};
