/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklist200ThreeData } from './updateChecklist200ThreeData';
import type { UpdateChecklist200ThreeMeta } from './updateChecklist200ThreeMeta';

export type UpdateChecklist200Three = {
  data: UpdateChecklist200ThreeData;
  meta: UpdateChecklist200ThreeMeta;
};
