/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklist200OneDataItemsItem } from './updateChecklist200OneDataItemsItem';
import type { UpdateChecklist200OneDataMetadata } from './updateChecklist200OneDataMetadata';
import type { UpdateChecklist200OneDataOptionsItem } from './updateChecklist200OneDataOptionsItem';

export type UpdateChecklist200OneData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: UpdateChecklist200OneDataOptionsItem[];
  items: UpdateChecklist200OneDataItemsItem[];
  metadata: UpdateChecklist200OneDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
