/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAttachment200OneData } from './updateAttachment200OneData';
import type { UpdateAttachment200OneMeta } from './updateAttachment200OneMeta';

export type UpdateAttachment200One = {
  data: UpdateAttachment200OneData;
  meta: UpdateAttachment200OneMeta;
};
