/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklist200OneData } from './updateChecklist200OneData';
import type { UpdateChecklist200OneMeta } from './updateChecklist200OneMeta';

export type UpdateChecklist200One = {
  data: UpdateChecklist200OneData;
  meta: UpdateChecklist200OneMeta;
};
