/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplicationItemBodyThreeMetadata } from './updateApplicationItemBodyThreeMetadata';

export type UpdateApplicationItemBodyThree = {
  ids?: string[];
  answer?: string;
  note?: string;
  quantity?: number | null;
  tagsIds?: string[];
  suggested?: boolean;
  suggestionSource?: string | null;
  workflowStatus?: string | null;
  metadata?: UpdateApplicationItemBodyThreeMetadata;
  updatedAt?: string;
};
