/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAttachment200TwoData } from './updateAttachment200TwoData';
import type { UpdateAttachment200TwoMeta } from './updateAttachment200TwoMeta';

export type UpdateAttachment200Two = {
  data: UpdateAttachment200TwoData;
  meta: UpdateAttachment200TwoMeta;
};
