/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrganizationMemberRoleBody = {
  /** The new role to be applied. This can be a string or array of strings representing the roles. Eg: ["admin", "sale"] */
  role: string | string[];
  /** The member id to apply the role update to. Eg: "member-id" */
  memberId: string;
  /** An optional organization ID which the member is a part of to apply the role update. If not provided, you must provide session headers to get the active organization. Eg: "organization-id" */
  organizationId?: string;
};
