/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplication200TwoDataAttachmentsItem } from './updateApplication200TwoDataAttachmentsItem';
import type { UpdateApplication200TwoDataItemsItem } from './updateApplication200TwoDataItemsItem';
import type { UpdateApplication200TwoDataMetadata } from './updateApplication200TwoDataMetadata';

export type UpdateApplication200TwoData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: UpdateApplication200TwoDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: UpdateApplication200TwoDataAttachmentsItem[];
  items: UpdateApplication200TwoDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
