/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChecklist200ThreeDataItemsItem } from './updateChecklist200ThreeDataItemsItem';
import type { UpdateChecklist200ThreeDataMetadata } from './updateChecklist200ThreeDataMetadata';
import type { UpdateChecklist200ThreeDataOptionsItem } from './updateChecklist200ThreeDataOptionsItem';

export type UpdateChecklist200ThreeData = {
  id: string;
  title: string;
  source: string | null;
  tagsIds: string[];
  options: UpdateChecklist200ThreeDataOptionsItem[];
  items: UpdateChecklist200ThreeDataItemsItem[];
  metadata: UpdateChecklist200ThreeDataMetadata;
  applicationsCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};
