/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplication200OneDataAttachmentsItem } from './updateApplication200OneDataAttachmentsItem';
import type { UpdateApplication200OneDataItemsItem } from './updateApplication200OneDataItemsItem';
import type { UpdateApplication200OneDataMetadata } from './updateApplication200OneDataMetadata';

export type UpdateApplication200OneData = {
  id: string;
  checklistId: string;
  tagsIds: string[];
  date: string;
  status: string;
  transcript: string | null;
  gallerySourceApplicationId: string | null;
  metadata: UpdateApplication200OneDataMetadata;
  answeredCount: number;
  totalCount: number;
  negativeCount: number;
  attachmentsCount: number;
  attachments: UpdateApplication200OneDataAttachmentsItem[];
  items: UpdateApplication200OneDataItemsItem[];
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
};
