/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateApplication200OneData } from './updateApplication200OneData';
import type { UpdateApplication200OneMeta } from './updateApplication200OneMeta';

export type UpdateApplication200One = {
  data: UpdateApplication200OneData;
  meta: UpdateApplication200OneMeta;
};
