/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of the OTP
 */
export type VerifyEmailWithOTPBodyType = typeof VerifyEmailWithOTPBodyType[keyof typeof VerifyEmailWithOTPBodyType];


export const VerifyEmailWithOTPBodyType = {
  'email-verification': 'email-verification',
  'sign-in': 'sign-in',
  'forget-password': 'forget-password',
  'change-email': 'change-email',
} as const;
