/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Send a verification OTP to an email
 */
export const SendEmailVerificationOTPBody = zod.strictObject({
  "email": zod.string().describe('Email address to send the OTP'),
  "type": zod.enum(['email-verification', 'sign-in', 'forget-password', 'change-email']).describe('Type of the OTP')
})

export const SendEmailVerificationOTPResponse = zod.strictObject({
  "success": zod.boolean().optional()
})

/**
 * Verify an email with an OTP
 */
export const VerifyEmailWithOTPBody = zod.strictObject({
  "email": zod.string().describe('Email address the OTP was sent to'),
  "type": zod.enum(['email-verification', 'sign-in', 'forget-password', 'change-email']).describe('Type of the OTP'),
  "otp": zod.string().describe('OTP to verify')
})

export const VerifyEmailWithOTPResponse = zod.strictObject({
  "success": zod.boolean().optional()
})

/**
 * Verify email with OTP
 */
export const PostApiAuthEmailOtpVerifyEmailBody = zod.strictObject({
  "email": zod.string().describe('Email address to verify'),
  "otp": zod.string().describe('OTP to verify')
})

export const postApiAuthEmailOtpVerifyEmailResponseUserEmailVerifiedDefault = false;

export const PostApiAuthEmailOtpVerifyEmailResponse = zod.strictObject({
  "status": zod.literal(true).describe('Indicates if the verification was successful'),
  "token": zod.string().nullable().describe('Session token if autoSignInAfterVerification is enabled, otherwise null'),
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(postApiAuthEmailOtpVerifyEmailResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
})
})

/**
 * Sign in with email and OTP
 */
export const SignInWithEmailOTPBody = zod.strictObject({
  "email": zod.string().describe('Email address to sign in'),
  "otp": zod.string().describe('OTP sent to the email'),
  "name": zod.string().optional().describe('User display name. Only used if the user is registering for the first time. Eg: "my-name"'),
  "image": zod.string().optional().describe('User profile image URL. Only used if the user is registering for the first time.')
})

export const signInWithEmailOTPResponseUserEmailVerifiedDefault = false;

export const SignInWithEmailOTPResponse = zod.strictObject({
  "token": zod.string().describe('Session token for the authenticated session'),
  "user": zod.strictObject({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "emailVerified": zod.boolean().default(signInWithEmailOTPResponseUserEmailVerifiedDefault),
  "image": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true})
})
})

/**
 * Request password reset with email and OTP
 */
export const RequestPasswordResetWithEmailOTPBody = zod.strictObject({
  "email": zod.string().describe('Email address to send the OTP')
})

export const RequestPasswordResetWithEmailOTPResponse = zod.strictObject({
  "success": zod.boolean().optional().describe('Indicates if the OTP was sent successfully')
})

/**
 * Deprecated: Use /email-otp/request-password-reset instead.
 */
export const ForgetPasswordWithEmailOTPBody = zod.strictObject({
  "email": zod.string().describe('Email address to send the OTP')
})

export const ForgetPasswordWithEmailOTPResponse = zod.strictObject({
  "success": zod.boolean().optional().describe('Indicates if the OTP was sent successfully')
})

/**
 * Reset password with email and OTP
 */
export const ResetPasswordWithEmailOTPBody = zod.strictObject({
  "email": zod.string().describe('Email address to reset the password'),
  "otp": zod.string().describe('OTP sent to the email'),
  "password": zod.string().describe('New password')
})

export const ResetPasswordWithEmailOTPResponse = zod.strictObject({
  "success": zod.boolean().optional()
})

/**
 * Request email change with verification OTP sent to the new email
 */
export const RequestEmailChangeWithEmailOTPBody = zod.strictObject({
  "newEmail": zod.string().describe('New email address to send the OTP'),
  "otp": zod.string().optional()
})

export const RequestEmailChangeWithEmailOTPResponse = zod.strictObject({
  "success": zod.boolean().optional()
})

/**
 * Verify new email with OTP and change the email if verification is successful
 */
export const ChangeEmailWithEmailOTPBody = zod.strictObject({
  "newEmail": zod.string().describe('New email address to verify and change to'),
  "otp": zod.string().describe('OTP sent to the new email')
})

export const ChangeEmailWithEmailOTPResponse = zod.strictObject({
  "success": zod.boolean().optional()
})

