/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vistoria API
 * Backend do app de vistoria. Auth por email-OTP + organizations (Better Auth em /api/auth). Projetos pertencem à organização; recursos de vistoria são escopados por :projectId no path.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ChangeEmailWithEmailOTP200,
  ChangeEmailWithEmailOTP400,
  ChangeEmailWithEmailOTP401,
  ChangeEmailWithEmailOTP403,
  ChangeEmailWithEmailOTP404,
  ChangeEmailWithEmailOTP429,
  ChangeEmailWithEmailOTP500,
  ChangeEmailWithEmailOTPBody,
  ForgetPasswordWithEmailOTP200,
  ForgetPasswordWithEmailOTP400,
  ForgetPasswordWithEmailOTP401,
  ForgetPasswordWithEmailOTP403,
  ForgetPasswordWithEmailOTP404,
  ForgetPasswordWithEmailOTP429,
  ForgetPasswordWithEmailOTP500,
  ForgetPasswordWithEmailOTPBody,
  PostApiAuthEmailOtpVerifyEmail200,
  PostApiAuthEmailOtpVerifyEmail400,
  PostApiAuthEmailOtpVerifyEmail401,
  PostApiAuthEmailOtpVerifyEmail403,
  PostApiAuthEmailOtpVerifyEmail404,
  PostApiAuthEmailOtpVerifyEmail429,
  PostApiAuthEmailOtpVerifyEmail500,
  PostApiAuthEmailOtpVerifyEmailBody,
  RequestEmailChangeWithEmailOTP200,
  RequestEmailChangeWithEmailOTP400,
  RequestEmailChangeWithEmailOTP401,
  RequestEmailChangeWithEmailOTP403,
  RequestEmailChangeWithEmailOTP404,
  RequestEmailChangeWithEmailOTP429,
  RequestEmailChangeWithEmailOTP500,
  RequestEmailChangeWithEmailOTPBody,
  RequestPasswordResetWithEmailOTP200,
  RequestPasswordResetWithEmailOTP400,
  RequestPasswordResetWithEmailOTP401,
  RequestPasswordResetWithEmailOTP403,
  RequestPasswordResetWithEmailOTP404,
  RequestPasswordResetWithEmailOTP429,
  RequestPasswordResetWithEmailOTP500,
  RequestPasswordResetWithEmailOTPBody,
  ResetPasswordWithEmailOTP200,
  ResetPasswordWithEmailOTP400,
  ResetPasswordWithEmailOTP401,
  ResetPasswordWithEmailOTP403,
  ResetPasswordWithEmailOTP404,
  ResetPasswordWithEmailOTP429,
  ResetPasswordWithEmailOTP500,
  ResetPasswordWithEmailOTPBody,
  SendEmailVerificationOTP200,
  SendEmailVerificationOTP400,
  SendEmailVerificationOTP401,
  SendEmailVerificationOTP403,
  SendEmailVerificationOTP404,
  SendEmailVerificationOTP429,
  SendEmailVerificationOTP500,
  SendEmailVerificationOTPBody,
  SignInWithEmailOTP200,
  SignInWithEmailOTP400,
  SignInWithEmailOTP401,
  SignInWithEmailOTP403,
  SignInWithEmailOTP404,
  SignInWithEmailOTP429,
  SignInWithEmailOTP500,
  SignInWithEmailOTPBody,
  VerifyEmailWithOTP200,
  VerifyEmailWithOTP400,
  VerifyEmailWithOTP401,
  VerifyEmailWithOTP403,
  VerifyEmailWithOTP404,
  VerifyEmailWithOTP429,
  VerifyEmailWithOTP500,
  VerifyEmailWithOTPBody
} from '../../models';

import { f } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type sendEmailVerificationOTPResponse200 = {
  data: SendEmailVerificationOTP200
  status: 200
}

export type sendEmailVerificationOTPResponse400 = {
  data: SendEmailVerificationOTP400
  status: 400
}

export type sendEmailVerificationOTPResponse401 = {
  data: SendEmailVerificationOTP401
  status: 401
}

export type sendEmailVerificationOTPResponse403 = {
  data: SendEmailVerificationOTP403
  status: 403
}

export type sendEmailVerificationOTPResponse404 = {
  data: SendEmailVerificationOTP404
  status: 404
}

export type sendEmailVerificationOTPResponse429 = {
  data: SendEmailVerificationOTP429
  status: 429
}

export type sendEmailVerificationOTPResponse500 = {
  data: SendEmailVerificationOTP500
  status: 500
}

export type sendEmailVerificationOTPResponseSuccess = (sendEmailVerificationOTPResponse200) & {
  headers: Headers;
};
export type sendEmailVerificationOTPResponseError = (sendEmailVerificationOTPResponse400 | sendEmailVerificationOTPResponse401 | sendEmailVerificationOTPResponse403 | sendEmailVerificationOTPResponse404 | sendEmailVerificationOTPResponse429 | sendEmailVerificationOTPResponse500) & {
  headers: Headers;
};

export type sendEmailVerificationOTPResponse = (sendEmailVerificationOTPResponseSuccess | sendEmailVerificationOTPResponseError)

export const getSendEmailVerificationOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/email-otp/send-verification-otp`
}

/**
 * Send a verification OTP to an email
 */
export const sendEmailVerificationOTP = async (sendEmailVerificationOTPBody: SendEmailVerificationOTPBody, options?: Parameters<typeof f>[1]): Promise<sendEmailVerificationOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<sendEmailVerificationOTPResponse>(getSendEmailVerificationOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(sendEmailVerificationOTPBody)
  }
);}





export const getSendEmailVerificationOTPMutationKey = () => ['sendEmailVerificationOTP'] as const;

export const getSendEmailVerificationOTPMutationOptions = <TError = SendEmailVerificationOTP400 | SendEmailVerificationOTP401 | SendEmailVerificationOTP403 | SendEmailVerificationOTP404 | SendEmailVerificationOTP429 | SendEmailVerificationOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailVerificationOTP>>, TError,SendEmailVerificationOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof sendEmailVerificationOTP>>, TError,SendEmailVerificationOTPMutationVariables, TContext> => {

const mutationKey = getSendEmailVerificationOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendEmailVerificationOTP>>, SendEmailVerificationOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  sendEmailVerificationOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendEmailVerificationOTPMutationResult = NonNullable<Awaited<ReturnType<typeof sendEmailVerificationOTP>>>
    export type SendEmailVerificationOTPMutationBody = SendEmailVerificationOTPBody
    export type SendEmailVerificationOTPMutationError = SendEmailVerificationOTP400 | SendEmailVerificationOTP401 | SendEmailVerificationOTP403 | SendEmailVerificationOTP404 | SendEmailVerificationOTP429 | SendEmailVerificationOTP500
    export type SendEmailVerificationOTPMutationVariables = {data: SendEmailVerificationOTPBody}

    export const useSendEmailVerificationOTP = <TError = SendEmailVerificationOTP400 | SendEmailVerificationOTP401 | SendEmailVerificationOTP403 | SendEmailVerificationOTP404 | SendEmailVerificationOTP429 | SendEmailVerificationOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailVerificationOTP>>, TError,SendEmailVerificationOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendEmailVerificationOTP>>,
        TError,
        SendEmailVerificationOTPMutationVariables,
        TContext
      > => {
      return useMutation(getSendEmailVerificationOTPMutationOptions(options), queryClient);
    }
    export type verifyEmailWithOTPResponse200 = {
  data: VerifyEmailWithOTP200
  status: 200
}

export type verifyEmailWithOTPResponse400 = {
  data: VerifyEmailWithOTP400
  status: 400
}

export type verifyEmailWithOTPResponse401 = {
  data: VerifyEmailWithOTP401
  status: 401
}

export type verifyEmailWithOTPResponse403 = {
  data: VerifyEmailWithOTP403
  status: 403
}

export type verifyEmailWithOTPResponse404 = {
  data: VerifyEmailWithOTP404
  status: 404
}

export type verifyEmailWithOTPResponse429 = {
  data: VerifyEmailWithOTP429
  status: 429
}

export type verifyEmailWithOTPResponse500 = {
  data: VerifyEmailWithOTP500
  status: 500
}

export type verifyEmailWithOTPResponseSuccess = (verifyEmailWithOTPResponse200) & {
  headers: Headers;
};
export type verifyEmailWithOTPResponseError = (verifyEmailWithOTPResponse400 | verifyEmailWithOTPResponse401 | verifyEmailWithOTPResponse403 | verifyEmailWithOTPResponse404 | verifyEmailWithOTPResponse429 | verifyEmailWithOTPResponse500) & {
  headers: Headers;
};

export type verifyEmailWithOTPResponse = (verifyEmailWithOTPResponseSuccess | verifyEmailWithOTPResponseError)

export const getVerifyEmailWithOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/email-otp/check-verification-otp`
}

/**
 * Verify an email with an OTP
 */
export const verifyEmailWithOTP = async (verifyEmailWithOTPBody: VerifyEmailWithOTPBody, options?: Parameters<typeof f>[1]): Promise<verifyEmailWithOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<verifyEmailWithOTPResponse>(getVerifyEmailWithOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(verifyEmailWithOTPBody)
  }
);}





export const getVerifyEmailWithOTPMutationKey = () => ['verifyEmailWithOTP'] as const;

export const getVerifyEmailWithOTPMutationOptions = <TError = VerifyEmailWithOTP400 | VerifyEmailWithOTP401 | VerifyEmailWithOTP403 | VerifyEmailWithOTP404 | VerifyEmailWithOTP429 | VerifyEmailWithOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyEmailWithOTP>>, TError,VerifyEmailWithOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyEmailWithOTP>>, TError,VerifyEmailWithOTPMutationVariables, TContext> => {

const mutationKey = getVerifyEmailWithOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyEmailWithOTP>>, VerifyEmailWithOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  verifyEmailWithOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VerifyEmailWithOTPMutationResult = NonNullable<Awaited<ReturnType<typeof verifyEmailWithOTP>>>
    export type VerifyEmailWithOTPMutationBody = VerifyEmailWithOTPBody
    export type VerifyEmailWithOTPMutationError = VerifyEmailWithOTP400 | VerifyEmailWithOTP401 | VerifyEmailWithOTP403 | VerifyEmailWithOTP404 | VerifyEmailWithOTP429 | VerifyEmailWithOTP500
    export type VerifyEmailWithOTPMutationVariables = {data: VerifyEmailWithOTPBody}

    export const useVerifyEmailWithOTP = <TError = VerifyEmailWithOTP400 | VerifyEmailWithOTP401 | VerifyEmailWithOTP403 | VerifyEmailWithOTP404 | VerifyEmailWithOTP429 | VerifyEmailWithOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyEmailWithOTP>>, TError,VerifyEmailWithOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyEmailWithOTP>>,
        TError,
        VerifyEmailWithOTPMutationVariables,
        TContext
      > => {
      return useMutation(getVerifyEmailWithOTPMutationOptions(options), queryClient);
    }
    export type postApiAuthEmailOtpVerifyEmailResponse200 = {
  data: PostApiAuthEmailOtpVerifyEmail200
  status: 200
}

export type postApiAuthEmailOtpVerifyEmailResponse400 = {
  data: PostApiAuthEmailOtpVerifyEmail400
  status: 400
}

export type postApiAuthEmailOtpVerifyEmailResponse401 = {
  data: PostApiAuthEmailOtpVerifyEmail401
  status: 401
}

export type postApiAuthEmailOtpVerifyEmailResponse403 = {
  data: PostApiAuthEmailOtpVerifyEmail403
  status: 403
}

export type postApiAuthEmailOtpVerifyEmailResponse404 = {
  data: PostApiAuthEmailOtpVerifyEmail404
  status: 404
}

export type postApiAuthEmailOtpVerifyEmailResponse429 = {
  data: PostApiAuthEmailOtpVerifyEmail429
  status: 429
}

export type postApiAuthEmailOtpVerifyEmailResponse500 = {
  data: PostApiAuthEmailOtpVerifyEmail500
  status: 500
}

export type postApiAuthEmailOtpVerifyEmailResponseSuccess = (postApiAuthEmailOtpVerifyEmailResponse200) & {
  headers: Headers;
};
export type postApiAuthEmailOtpVerifyEmailResponseError = (postApiAuthEmailOtpVerifyEmailResponse400 | postApiAuthEmailOtpVerifyEmailResponse401 | postApiAuthEmailOtpVerifyEmailResponse403 | postApiAuthEmailOtpVerifyEmailResponse404 | postApiAuthEmailOtpVerifyEmailResponse429 | postApiAuthEmailOtpVerifyEmailResponse500) & {
  headers: Headers;
};

export type postApiAuthEmailOtpVerifyEmailResponse = (postApiAuthEmailOtpVerifyEmailResponseSuccess | postApiAuthEmailOtpVerifyEmailResponseError)

export const getPostApiAuthEmailOtpVerifyEmailUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/email-otp/verify-email`
}

/**
 * Verify email with OTP
 */
export const postApiAuthEmailOtpVerifyEmail = async (postApiAuthEmailOtpVerifyEmailBody: PostApiAuthEmailOtpVerifyEmailBody, options?: Parameters<typeof f>[1]): Promise<postApiAuthEmailOtpVerifyEmailResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<postApiAuthEmailOtpVerifyEmailResponse>(getPostApiAuthEmailOtpVerifyEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postApiAuthEmailOtpVerifyEmailBody)
  }
);}





export const getPostApiAuthEmailOtpVerifyEmailMutationKey = () => ['postApiAuthEmailOtpVerifyEmail'] as const;

export const getPostApiAuthEmailOtpVerifyEmailMutationOptions = <TError = PostApiAuthEmailOtpVerifyEmail400 | PostApiAuthEmailOtpVerifyEmail401 | PostApiAuthEmailOtpVerifyEmail403 | PostApiAuthEmailOtpVerifyEmail404 | PostApiAuthEmailOtpVerifyEmail429 | PostApiAuthEmailOtpVerifyEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthEmailOtpVerifyEmail>>, TError,PostApiAuthEmailOtpVerifyEmailMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthEmailOtpVerifyEmail>>, TError,PostApiAuthEmailOtpVerifyEmailMutationVariables, TContext> => {

const mutationKey = getPostApiAuthEmailOtpVerifyEmailMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthEmailOtpVerifyEmail>>, PostApiAuthEmailOtpVerifyEmailMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthEmailOtpVerifyEmail(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthEmailOtpVerifyEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthEmailOtpVerifyEmail>>>
    export type PostApiAuthEmailOtpVerifyEmailMutationBody = PostApiAuthEmailOtpVerifyEmailBody
    export type PostApiAuthEmailOtpVerifyEmailMutationError = PostApiAuthEmailOtpVerifyEmail400 | PostApiAuthEmailOtpVerifyEmail401 | PostApiAuthEmailOtpVerifyEmail403 | PostApiAuthEmailOtpVerifyEmail404 | PostApiAuthEmailOtpVerifyEmail429 | PostApiAuthEmailOtpVerifyEmail500
    export type PostApiAuthEmailOtpVerifyEmailMutationVariables = {data: PostApiAuthEmailOtpVerifyEmailBody}

    export const usePostApiAuthEmailOtpVerifyEmail = <TError = PostApiAuthEmailOtpVerifyEmail400 | PostApiAuthEmailOtpVerifyEmail401 | PostApiAuthEmailOtpVerifyEmail403 | PostApiAuthEmailOtpVerifyEmail404 | PostApiAuthEmailOtpVerifyEmail429 | PostApiAuthEmailOtpVerifyEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthEmailOtpVerifyEmail>>, TError,PostApiAuthEmailOtpVerifyEmailMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthEmailOtpVerifyEmail>>,
        TError,
        PostApiAuthEmailOtpVerifyEmailMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAuthEmailOtpVerifyEmailMutationOptions(options), queryClient);
    }
    export type signInWithEmailOTPResponse200 = {
  data: SignInWithEmailOTP200
  status: 200
}

export type signInWithEmailOTPResponse400 = {
  data: SignInWithEmailOTP400
  status: 400
}

export type signInWithEmailOTPResponse401 = {
  data: SignInWithEmailOTP401
  status: 401
}

export type signInWithEmailOTPResponse403 = {
  data: SignInWithEmailOTP403
  status: 403
}

export type signInWithEmailOTPResponse404 = {
  data: SignInWithEmailOTP404
  status: 404
}

export type signInWithEmailOTPResponse429 = {
  data: SignInWithEmailOTP429
  status: 429
}

export type signInWithEmailOTPResponse500 = {
  data: SignInWithEmailOTP500
  status: 500
}

export type signInWithEmailOTPResponseSuccess = (signInWithEmailOTPResponse200) & {
  headers: Headers;
};
export type signInWithEmailOTPResponseError = (signInWithEmailOTPResponse400 | signInWithEmailOTPResponse401 | signInWithEmailOTPResponse403 | signInWithEmailOTPResponse404 | signInWithEmailOTPResponse429 | signInWithEmailOTPResponse500) & {
  headers: Headers;
};

export type signInWithEmailOTPResponse = (signInWithEmailOTPResponseSuccess | signInWithEmailOTPResponseError)

export const getSignInWithEmailOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/sign-in/email-otp`
}

/**
 * Sign in with email and OTP
 */
export const signInWithEmailOTP = async (signInWithEmailOTPBody: SignInWithEmailOTPBody, options?: Parameters<typeof f>[1]): Promise<signInWithEmailOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<signInWithEmailOTPResponse>(getSignInWithEmailOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(signInWithEmailOTPBody)
  }
);}





export const getSignInWithEmailOTPMutationKey = () => ['signInWithEmailOTP'] as const;

export const getSignInWithEmailOTPMutationOptions = <TError = SignInWithEmailOTP400 | SignInWithEmailOTP401 | SignInWithEmailOTP403 | SignInWithEmailOTP404 | SignInWithEmailOTP429 | SignInWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signInWithEmailOTP>>, TError,SignInWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof signInWithEmailOTP>>, TError,SignInWithEmailOTPMutationVariables, TContext> => {

const mutationKey = getSignInWithEmailOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signInWithEmailOTP>>, SignInWithEmailOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  signInWithEmailOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignInWithEmailOTPMutationResult = NonNullable<Awaited<ReturnType<typeof signInWithEmailOTP>>>
    export type SignInWithEmailOTPMutationBody = SignInWithEmailOTPBody
    export type SignInWithEmailOTPMutationError = SignInWithEmailOTP400 | SignInWithEmailOTP401 | SignInWithEmailOTP403 | SignInWithEmailOTP404 | SignInWithEmailOTP429 | SignInWithEmailOTP500
    export type SignInWithEmailOTPMutationVariables = {data: SignInWithEmailOTPBody}

    export const useSignInWithEmailOTP = <TError = SignInWithEmailOTP400 | SignInWithEmailOTP401 | SignInWithEmailOTP403 | SignInWithEmailOTP404 | SignInWithEmailOTP429 | SignInWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signInWithEmailOTP>>, TError,SignInWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signInWithEmailOTP>>,
        TError,
        SignInWithEmailOTPMutationVariables,
        TContext
      > => {
      return useMutation(getSignInWithEmailOTPMutationOptions(options), queryClient);
    }
    export type requestPasswordResetWithEmailOTPResponse200 = {
  data: RequestPasswordResetWithEmailOTP200
  status: 200
}

export type requestPasswordResetWithEmailOTPResponse400 = {
  data: RequestPasswordResetWithEmailOTP400
  status: 400
}

export type requestPasswordResetWithEmailOTPResponse401 = {
  data: RequestPasswordResetWithEmailOTP401
  status: 401
}

export type requestPasswordResetWithEmailOTPResponse403 = {
  data: RequestPasswordResetWithEmailOTP403
  status: 403
}

export type requestPasswordResetWithEmailOTPResponse404 = {
  data: RequestPasswordResetWithEmailOTP404
  status: 404
}

export type requestPasswordResetWithEmailOTPResponse429 = {
  data: RequestPasswordResetWithEmailOTP429
  status: 429
}

export type requestPasswordResetWithEmailOTPResponse500 = {
  data: RequestPasswordResetWithEmailOTP500
  status: 500
}

export type requestPasswordResetWithEmailOTPResponseSuccess = (requestPasswordResetWithEmailOTPResponse200) & {
  headers: Headers;
};
export type requestPasswordResetWithEmailOTPResponseError = (requestPasswordResetWithEmailOTPResponse400 | requestPasswordResetWithEmailOTPResponse401 | requestPasswordResetWithEmailOTPResponse403 | requestPasswordResetWithEmailOTPResponse404 | requestPasswordResetWithEmailOTPResponse429 | requestPasswordResetWithEmailOTPResponse500) & {
  headers: Headers;
};

export type requestPasswordResetWithEmailOTPResponse = (requestPasswordResetWithEmailOTPResponseSuccess | requestPasswordResetWithEmailOTPResponseError)

export const getRequestPasswordResetWithEmailOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/email-otp/request-password-reset`
}

/**
 * Request password reset with email and OTP
 */
export const requestPasswordResetWithEmailOTP = async (requestPasswordResetWithEmailOTPBody: RequestPasswordResetWithEmailOTPBody, options?: Parameters<typeof f>[1]): Promise<requestPasswordResetWithEmailOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<requestPasswordResetWithEmailOTPResponse>(getRequestPasswordResetWithEmailOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(requestPasswordResetWithEmailOTPBody)
  }
);}





export const getRequestPasswordResetWithEmailOTPMutationKey = () => ['requestPasswordResetWithEmailOTP'] as const;

export const getRequestPasswordResetWithEmailOTPMutationOptions = <TError = RequestPasswordResetWithEmailOTP400 | RequestPasswordResetWithEmailOTP401 | RequestPasswordResetWithEmailOTP403 | RequestPasswordResetWithEmailOTP404 | RequestPasswordResetWithEmailOTP429 | RequestPasswordResetWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetWithEmailOTP>>, TError,RequestPasswordResetWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetWithEmailOTP>>, TError,RequestPasswordResetWithEmailOTPMutationVariables, TContext> => {

const mutationKey = getRequestPasswordResetWithEmailOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestPasswordResetWithEmailOTP>>, RequestPasswordResetWithEmailOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  requestPasswordResetWithEmailOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RequestPasswordResetWithEmailOTPMutationResult = NonNullable<Awaited<ReturnType<typeof requestPasswordResetWithEmailOTP>>>
    export type RequestPasswordResetWithEmailOTPMutationBody = RequestPasswordResetWithEmailOTPBody
    export type RequestPasswordResetWithEmailOTPMutationError = RequestPasswordResetWithEmailOTP400 | RequestPasswordResetWithEmailOTP401 | RequestPasswordResetWithEmailOTP403 | RequestPasswordResetWithEmailOTP404 | RequestPasswordResetWithEmailOTP429 | RequestPasswordResetWithEmailOTP500
    export type RequestPasswordResetWithEmailOTPMutationVariables = {data: RequestPasswordResetWithEmailOTPBody}

    export const useRequestPasswordResetWithEmailOTP = <TError = RequestPasswordResetWithEmailOTP400 | RequestPasswordResetWithEmailOTP401 | RequestPasswordResetWithEmailOTP403 | RequestPasswordResetWithEmailOTP404 | RequestPasswordResetWithEmailOTP429 | RequestPasswordResetWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetWithEmailOTP>>, TError,RequestPasswordResetWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestPasswordResetWithEmailOTP>>,
        TError,
        RequestPasswordResetWithEmailOTPMutationVariables,
        TContext
      > => {
      return useMutation(getRequestPasswordResetWithEmailOTPMutationOptions(options), queryClient);
    }
    export type forgetPasswordWithEmailOTPResponse200 = {
  data: ForgetPasswordWithEmailOTP200
  status: 200
}

export type forgetPasswordWithEmailOTPResponse400 = {
  data: ForgetPasswordWithEmailOTP400
  status: 400
}

export type forgetPasswordWithEmailOTPResponse401 = {
  data: ForgetPasswordWithEmailOTP401
  status: 401
}

export type forgetPasswordWithEmailOTPResponse403 = {
  data: ForgetPasswordWithEmailOTP403
  status: 403
}

export type forgetPasswordWithEmailOTPResponse404 = {
  data: ForgetPasswordWithEmailOTP404
  status: 404
}

export type forgetPasswordWithEmailOTPResponse429 = {
  data: ForgetPasswordWithEmailOTP429
  status: 429
}

export type forgetPasswordWithEmailOTPResponse500 = {
  data: ForgetPasswordWithEmailOTP500
  status: 500
}

export type forgetPasswordWithEmailOTPResponseSuccess = (forgetPasswordWithEmailOTPResponse200) & {
  headers: Headers;
};
export type forgetPasswordWithEmailOTPResponseError = (forgetPasswordWithEmailOTPResponse400 | forgetPasswordWithEmailOTPResponse401 | forgetPasswordWithEmailOTPResponse403 | forgetPasswordWithEmailOTPResponse404 | forgetPasswordWithEmailOTPResponse429 | forgetPasswordWithEmailOTPResponse500) & {
  headers: Headers;
};

export type forgetPasswordWithEmailOTPResponse = (forgetPasswordWithEmailOTPResponseSuccess | forgetPasswordWithEmailOTPResponseError)

export const getForgetPasswordWithEmailOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/forget-password/email-otp`
}

/**
 * Deprecated: Use /email-otp/request-password-reset instead.
 */
export const forgetPasswordWithEmailOTP = async (forgetPasswordWithEmailOTPBody: ForgetPasswordWithEmailOTPBody, options?: Parameters<typeof f>[1]): Promise<forgetPasswordWithEmailOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<forgetPasswordWithEmailOTPResponse>(getForgetPasswordWithEmailOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(forgetPasswordWithEmailOTPBody)
  }
);}





export const getForgetPasswordWithEmailOTPMutationKey = () => ['forgetPasswordWithEmailOTP'] as const;

export const getForgetPasswordWithEmailOTPMutationOptions = <TError = ForgetPasswordWithEmailOTP400 | ForgetPasswordWithEmailOTP401 | ForgetPasswordWithEmailOTP403 | ForgetPasswordWithEmailOTP404 | ForgetPasswordWithEmailOTP429 | ForgetPasswordWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgetPasswordWithEmailOTP>>, TError,ForgetPasswordWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof forgetPasswordWithEmailOTP>>, TError,ForgetPasswordWithEmailOTPMutationVariables, TContext> => {

const mutationKey = getForgetPasswordWithEmailOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof forgetPasswordWithEmailOTP>>, ForgetPasswordWithEmailOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  forgetPasswordWithEmailOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ForgetPasswordWithEmailOTPMutationResult = NonNullable<Awaited<ReturnType<typeof forgetPasswordWithEmailOTP>>>
    export type ForgetPasswordWithEmailOTPMutationBody = ForgetPasswordWithEmailOTPBody
    export type ForgetPasswordWithEmailOTPMutationError = ForgetPasswordWithEmailOTP400 | ForgetPasswordWithEmailOTP401 | ForgetPasswordWithEmailOTP403 | ForgetPasswordWithEmailOTP404 | ForgetPasswordWithEmailOTP429 | ForgetPasswordWithEmailOTP500
    export type ForgetPasswordWithEmailOTPMutationVariables = {data: ForgetPasswordWithEmailOTPBody}

    export const useForgetPasswordWithEmailOTP = <TError = ForgetPasswordWithEmailOTP400 | ForgetPasswordWithEmailOTP401 | ForgetPasswordWithEmailOTP403 | ForgetPasswordWithEmailOTP404 | ForgetPasswordWithEmailOTP429 | ForgetPasswordWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgetPasswordWithEmailOTP>>, TError,ForgetPasswordWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof forgetPasswordWithEmailOTP>>,
        TError,
        ForgetPasswordWithEmailOTPMutationVariables,
        TContext
      > => {
      return useMutation(getForgetPasswordWithEmailOTPMutationOptions(options), queryClient);
    }
    export type resetPasswordWithEmailOTPResponse200 = {
  data: ResetPasswordWithEmailOTP200
  status: 200
}

export type resetPasswordWithEmailOTPResponse400 = {
  data: ResetPasswordWithEmailOTP400
  status: 400
}

export type resetPasswordWithEmailOTPResponse401 = {
  data: ResetPasswordWithEmailOTP401
  status: 401
}

export type resetPasswordWithEmailOTPResponse403 = {
  data: ResetPasswordWithEmailOTP403
  status: 403
}

export type resetPasswordWithEmailOTPResponse404 = {
  data: ResetPasswordWithEmailOTP404
  status: 404
}

export type resetPasswordWithEmailOTPResponse429 = {
  data: ResetPasswordWithEmailOTP429
  status: 429
}

export type resetPasswordWithEmailOTPResponse500 = {
  data: ResetPasswordWithEmailOTP500
  status: 500
}

export type resetPasswordWithEmailOTPResponseSuccess = (resetPasswordWithEmailOTPResponse200) & {
  headers: Headers;
};
export type resetPasswordWithEmailOTPResponseError = (resetPasswordWithEmailOTPResponse400 | resetPasswordWithEmailOTPResponse401 | resetPasswordWithEmailOTPResponse403 | resetPasswordWithEmailOTPResponse404 | resetPasswordWithEmailOTPResponse429 | resetPasswordWithEmailOTPResponse500) & {
  headers: Headers;
};

export type resetPasswordWithEmailOTPResponse = (resetPasswordWithEmailOTPResponseSuccess | resetPasswordWithEmailOTPResponseError)

export const getResetPasswordWithEmailOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/email-otp/reset-password`
}

/**
 * Reset password with email and OTP
 */
export const resetPasswordWithEmailOTP = async (resetPasswordWithEmailOTPBody: ResetPasswordWithEmailOTPBody, options?: Parameters<typeof f>[1]): Promise<resetPasswordWithEmailOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<resetPasswordWithEmailOTPResponse>(getResetPasswordWithEmailOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(resetPasswordWithEmailOTPBody)
  }
);}





export const getResetPasswordWithEmailOTPMutationKey = () => ['resetPasswordWithEmailOTP'] as const;

export const getResetPasswordWithEmailOTPMutationOptions = <TError = ResetPasswordWithEmailOTP400 | ResetPasswordWithEmailOTP401 | ResetPasswordWithEmailOTP403 | ResetPasswordWithEmailOTP404 | ResetPasswordWithEmailOTP429 | ResetPasswordWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPasswordWithEmailOTP>>, TError,ResetPasswordWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPasswordWithEmailOTP>>, TError,ResetPasswordWithEmailOTPMutationVariables, TContext> => {

const mutationKey = getResetPasswordWithEmailOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPasswordWithEmailOTP>>, ResetPasswordWithEmailOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  resetPasswordWithEmailOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetPasswordWithEmailOTPMutationResult = NonNullable<Awaited<ReturnType<typeof resetPasswordWithEmailOTP>>>
    export type ResetPasswordWithEmailOTPMutationBody = ResetPasswordWithEmailOTPBody
    export type ResetPasswordWithEmailOTPMutationError = ResetPasswordWithEmailOTP400 | ResetPasswordWithEmailOTP401 | ResetPasswordWithEmailOTP403 | ResetPasswordWithEmailOTP404 | ResetPasswordWithEmailOTP429 | ResetPasswordWithEmailOTP500
    export type ResetPasswordWithEmailOTPMutationVariables = {data: ResetPasswordWithEmailOTPBody}

    export const useResetPasswordWithEmailOTP = <TError = ResetPasswordWithEmailOTP400 | ResetPasswordWithEmailOTP401 | ResetPasswordWithEmailOTP403 | ResetPasswordWithEmailOTP404 | ResetPasswordWithEmailOTP429 | ResetPasswordWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPasswordWithEmailOTP>>, TError,ResetPasswordWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetPasswordWithEmailOTP>>,
        TError,
        ResetPasswordWithEmailOTPMutationVariables,
        TContext
      > => {
      return useMutation(getResetPasswordWithEmailOTPMutationOptions(options), queryClient);
    }
    export type requestEmailChangeWithEmailOTPResponse200 = {
  data: RequestEmailChangeWithEmailOTP200
  status: 200
}

export type requestEmailChangeWithEmailOTPResponse400 = {
  data: RequestEmailChangeWithEmailOTP400
  status: 400
}

export type requestEmailChangeWithEmailOTPResponse401 = {
  data: RequestEmailChangeWithEmailOTP401
  status: 401
}

export type requestEmailChangeWithEmailOTPResponse403 = {
  data: RequestEmailChangeWithEmailOTP403
  status: 403
}

export type requestEmailChangeWithEmailOTPResponse404 = {
  data: RequestEmailChangeWithEmailOTP404
  status: 404
}

export type requestEmailChangeWithEmailOTPResponse429 = {
  data: RequestEmailChangeWithEmailOTP429
  status: 429
}

export type requestEmailChangeWithEmailOTPResponse500 = {
  data: RequestEmailChangeWithEmailOTP500
  status: 500
}

export type requestEmailChangeWithEmailOTPResponseSuccess = (requestEmailChangeWithEmailOTPResponse200) & {
  headers: Headers;
};
export type requestEmailChangeWithEmailOTPResponseError = (requestEmailChangeWithEmailOTPResponse400 | requestEmailChangeWithEmailOTPResponse401 | requestEmailChangeWithEmailOTPResponse403 | requestEmailChangeWithEmailOTPResponse404 | requestEmailChangeWithEmailOTPResponse429 | requestEmailChangeWithEmailOTPResponse500) & {
  headers: Headers;
};

export type requestEmailChangeWithEmailOTPResponse = (requestEmailChangeWithEmailOTPResponseSuccess | requestEmailChangeWithEmailOTPResponseError)

export const getRequestEmailChangeWithEmailOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/email-otp/request-email-change`
}

/**
 * Request email change with verification OTP sent to the new email
 */
export const requestEmailChangeWithEmailOTP = async (requestEmailChangeWithEmailOTPBody: RequestEmailChangeWithEmailOTPBody, options?: Parameters<typeof f>[1]): Promise<requestEmailChangeWithEmailOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<requestEmailChangeWithEmailOTPResponse>(getRequestEmailChangeWithEmailOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(requestEmailChangeWithEmailOTPBody)
  }
);}





export const getRequestEmailChangeWithEmailOTPMutationKey = () => ['requestEmailChangeWithEmailOTP'] as const;

export const getRequestEmailChangeWithEmailOTPMutationOptions = <TError = RequestEmailChangeWithEmailOTP400 | RequestEmailChangeWithEmailOTP401 | RequestEmailChangeWithEmailOTP403 | RequestEmailChangeWithEmailOTP404 | RequestEmailChangeWithEmailOTP429 | RequestEmailChangeWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestEmailChangeWithEmailOTP>>, TError,RequestEmailChangeWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof requestEmailChangeWithEmailOTP>>, TError,RequestEmailChangeWithEmailOTPMutationVariables, TContext> => {

const mutationKey = getRequestEmailChangeWithEmailOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestEmailChangeWithEmailOTP>>, RequestEmailChangeWithEmailOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  requestEmailChangeWithEmailOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RequestEmailChangeWithEmailOTPMutationResult = NonNullable<Awaited<ReturnType<typeof requestEmailChangeWithEmailOTP>>>
    export type RequestEmailChangeWithEmailOTPMutationBody = RequestEmailChangeWithEmailOTPBody
    export type RequestEmailChangeWithEmailOTPMutationError = RequestEmailChangeWithEmailOTP400 | RequestEmailChangeWithEmailOTP401 | RequestEmailChangeWithEmailOTP403 | RequestEmailChangeWithEmailOTP404 | RequestEmailChangeWithEmailOTP429 | RequestEmailChangeWithEmailOTP500
    export type RequestEmailChangeWithEmailOTPMutationVariables = {data: RequestEmailChangeWithEmailOTPBody}

    export const useRequestEmailChangeWithEmailOTP = <TError = RequestEmailChangeWithEmailOTP400 | RequestEmailChangeWithEmailOTP401 | RequestEmailChangeWithEmailOTP403 | RequestEmailChangeWithEmailOTP404 | RequestEmailChangeWithEmailOTP429 | RequestEmailChangeWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestEmailChangeWithEmailOTP>>, TError,RequestEmailChangeWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestEmailChangeWithEmailOTP>>,
        TError,
        RequestEmailChangeWithEmailOTPMutationVariables,
        TContext
      > => {
      return useMutation(getRequestEmailChangeWithEmailOTPMutationOptions(options), queryClient);
    }
    export type changeEmailWithEmailOTPResponse200 = {
  data: ChangeEmailWithEmailOTP200
  status: 200
}

export type changeEmailWithEmailOTPResponse400 = {
  data: ChangeEmailWithEmailOTP400
  status: 400
}

export type changeEmailWithEmailOTPResponse401 = {
  data: ChangeEmailWithEmailOTP401
  status: 401
}

export type changeEmailWithEmailOTPResponse403 = {
  data: ChangeEmailWithEmailOTP403
  status: 403
}

export type changeEmailWithEmailOTPResponse404 = {
  data: ChangeEmailWithEmailOTP404
  status: 404
}

export type changeEmailWithEmailOTPResponse429 = {
  data: ChangeEmailWithEmailOTP429
  status: 429
}

export type changeEmailWithEmailOTPResponse500 = {
  data: ChangeEmailWithEmailOTP500
  status: 500
}

export type changeEmailWithEmailOTPResponseSuccess = (changeEmailWithEmailOTPResponse200) & {
  headers: Headers;
};
export type changeEmailWithEmailOTPResponseError = (changeEmailWithEmailOTPResponse400 | changeEmailWithEmailOTPResponse401 | changeEmailWithEmailOTPResponse403 | changeEmailWithEmailOTPResponse404 | changeEmailWithEmailOTPResponse429 | changeEmailWithEmailOTPResponse500) & {
  headers: Headers;
};

export type changeEmailWithEmailOTPResponse = (changeEmailWithEmailOTPResponseSuccess | changeEmailWithEmailOTPResponseError)

export const getChangeEmailWithEmailOTPUrl = () => {




  return `${process.env.EXPO_PUBLIC_BACKEND_BASE_URL ?? 'http://localhost:3000'}/api/auth/email-otp/change-email`
}

/**
 * Verify new email with OTP and change the email if verification is successful
 */
export const changeEmailWithEmailOTP = async (changeEmailWithEmailOTPBody: ChangeEmailWithEmailOTPBody, options?: Parameters<typeof f>[1]): Promise<changeEmailWithEmailOTPResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return f<changeEmailWithEmailOTPResponse>(getChangeEmailWithEmailOTPUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(changeEmailWithEmailOTPBody)
  }
);}





export const getChangeEmailWithEmailOTPMutationKey = () => ['changeEmailWithEmailOTP'] as const;

export const getChangeEmailWithEmailOTPMutationOptions = <TError = ChangeEmailWithEmailOTP400 | ChangeEmailWithEmailOTP401 | ChangeEmailWithEmailOTP403 | ChangeEmailWithEmailOTP404 | ChangeEmailWithEmailOTP429 | ChangeEmailWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeEmailWithEmailOTP>>, TError,ChangeEmailWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
): UseMutationOptions<Awaited<ReturnType<typeof changeEmailWithEmailOTP>>, TError,ChangeEmailWithEmailOTPMutationVariables, TContext> => {

const mutationKey = getChangeEmailWithEmailOTPMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeEmailWithEmailOTP>>, ChangeEmailWithEmailOTPMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  changeEmailWithEmailOTP(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChangeEmailWithEmailOTPMutationResult = NonNullable<Awaited<ReturnType<typeof changeEmailWithEmailOTP>>>
    export type ChangeEmailWithEmailOTPMutationBody = ChangeEmailWithEmailOTPBody
    export type ChangeEmailWithEmailOTPMutationError = ChangeEmailWithEmailOTP400 | ChangeEmailWithEmailOTP401 | ChangeEmailWithEmailOTP403 | ChangeEmailWithEmailOTP404 | ChangeEmailWithEmailOTP429 | ChangeEmailWithEmailOTP500
    export type ChangeEmailWithEmailOTPMutationVariables = {data: ChangeEmailWithEmailOTPBody}

    export const useChangeEmailWithEmailOTP = <TError = ChangeEmailWithEmailOTP400 | ChangeEmailWithEmailOTP401 | ChangeEmailWithEmailOTP403 | ChangeEmailWithEmailOTP404 | ChangeEmailWithEmailOTP429 | ChangeEmailWithEmailOTP500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeEmailWithEmailOTP>>, TError,ChangeEmailWithEmailOTPMutationVariables, TContext>, request?: SecondParameter<typeof f>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeEmailWithEmailOTP>>,
        TError,
        ChangeEmailWithEmailOTPMutationVariables,
        TContext
      > => {
      return useMutation(getChangeEmailWithEmailOTPMutationOptions(options), queryClient);
    }
